### ISSUE TITLE
Get mail server up and running

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#1]
# Goal
When someone sends an email to registrar@exmachinis.com they are given a player account with three drones and provided a list of these drones in a welcome email sent from registrar@exmachinis.com. 

# Specifics
* An SQL **Email Table** will be used to store the contents of all incoming mail.
* An SQL **User Table** will be created to hold the email addresses and registration dates of all players.
* An SQL **Drone Table** will be used to link unique drone IDs to the owner's email address.
* A **Mail Handler** application will run continuously in the background to place incoming mail into the database.
* A **Registrar** application will run continuously in the background to respond to new registration requests (emails) as they appear in the database by creating a new user account, creating and linking new drones to the user account, and emailing the user about their new account and drones.
* The **Registrar** application will remind users of their existing accounts if they already have one.

# Documentation
Record details of [email server configuration](https://github.com/Darwin-River/Ex-Machinis/wiki/EmailServer) and [database structure](https://github.com/Darwin-River/Ex-Machinis/wiki/DatabaseStructure) in the wiki.

**Comment by freelancefrivas** [comment]
A mail handler composed of a mail server and a PHP script ran by a cron job now processes registrations and commands sent to drones. The users accounts are created with a company (without name) and three drones, storing the sender's name as user name. When a mail sent to a drone's email is received, everything between "script" tags is stored on the "commands" table.
