### ISSUE TITLE
Allowing abort and reset meta commands to process code

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#102]
It would be very helpful if the \<abort\> and \<reset\> meta commands could accept and process FORTH code just like the \<run> command.  

For example, the user could send any of the following instructions to their drone:
\<run\> 2 2 + .\</run\>
\<abort> 2 2 + . \</abort>
\<reset> 2 2 + . \</reset>

The only difference between the above meta commands would be that the run command will only execute the code if the drone is not doing anything else.  The abort command will stop any active processes before executing the accompanying code.  The reset command would completely reset the drone's VM before running the code. Of course, the user would still have the option of sending \<abort> and \<reset> without any code.

I tried to implement this myself.  But the source code appears to handle \<run> differently than the other meta commands, by extracting the code early on in the process (perhaps at the email server?) and then passing it to engine.c where the decision is made whether to treat the emailed instruction as a meta command or as FORTH code.  In fact, when I tried sending the following text to my drone, it ended up interpreting the reset command contained within the run brackets and resetting the VM, which really shouldn't happen because meta commands cannot be nested withing other meta commands:

\<run> \<reset> 2 4 + . \</run>

The \<run> command should really be handled like any of the other meta commands. 

Carlos, would you be able to help with these changes?

**Comment by crodnun** [comment]
Hi @darozak ,  the requested feature should be in place now (at advolition server).

We can now execute the following commands from email:

```
<abort>
```

or with command:

```
<abort>2 3 + .</abort>
```

The same for reset:

```
<reset>
```

or including an embedded command:

```
<reset>3 7 * .</reset>
```

Test it out and let me know if it works as you expected.

Just FYI, I have modified the PHP files that deal with the email text parsing to insert into DB the commands correctly.

If we have an abort or reset, this is the very first command inserted. Then, we insert the embedded one, and both are executed in this order, always the meta-command first.

Test it out and let me know if this is what you needed there.

**Comment by darozak** [comment]
Awesome! This works perfectly!  Thanks for making these changes.
