### ISSUE TITLE
Event engine not processing pull request correctly

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#107]
Bioworks drone number 151 (Arrow) tried to pull 1 unit of iron ore from Avalon drone number 52 (Sport) using the command: \<run> 1 1 52 11 perform \</run>.  At the time, Sport has an active sell bid for iron ore, which stipulates it will keep 1 u of iron ore and sell the rest for 10 credits each.  Sport has 4 u iron ore in cargo. 

![200422 Sport cargo and events](https://user-images.githubusercontent.com/33500329/79978269-a7382e00-846d-11ea-82e7-b8710e7f489a.PNG)

The online sell bid correctly shows a volume of 3 units for Sport's active sell bid:

![200422 Sell Orders](https://user-images.githubusercontent.com/33500329/79978282-ab644b80-846d-11ea-8fea-7f4acbd864d6.PNG)

However, when the Event Engine processes the pull event, it uses the following logic to determine the pull request cannot be completed:
```
* 22/04/2020,11:31:10.223 [0] Event [308] represents a market transaction between drone [151] and drone [52]
* 22/04/2020,11:31:10.223 [0] Processing market transaction at event [308], drone [52], user [18] is selling [-1] units of resource [1] to drone [52], user [18]
* 22/04/2020,11:31:10.223 [0] Getting previous event for event_id [308] and filter type [3] ...
* 22/04/2020,11:31:10.223 [0] TIMESTAMP [1587555065] => DATE [2020-04-22 11:31:05]
* 22/04/2020,11:31:10.223 [0] Running query [SELECT * from events where drone = 52 and event_type = 4 and outcome = 1 and resource = 1;]
* 22/04/2020,11:31:10.223 [0] [2] previous event found
* 22/04/2020,11:31:10.223 [0] Date [2020-02-22 23:26:21] converted to:  year, month, day, hour, min ,sec [120-1-22 23:26:21]
* 22/04/2020,11:31:10.223 [0] Converting date into epoch [2020-02-22 23:26:21] using format [%F %T], result = [1582413981], conversion_result = []
* 22/04/2020,11:31:10.223 [0] drone [52], has [1] units of resource [1], needs to keep [2], could sell [0]
* 22/04/2020,11:31:10.223 [0] WARNING: drone [52] CAN NOT SELL [1] units of resource [1] (operation forbidden, can only sell [0])
* 22/04/2020,11:31:10.224 [0] Action [325] aborted
```

I see two potential errors here.  First, the EE seems to think that drone 52 is selling -1 units of iron ore to its self (could -1 represent the depletion from its cargo?):
```
* 22/04/2020,11:31:10.223 [0] Processing market transaction at event [308], drone [52], user [18] is selling [-1] units of resource [1] to drone [52], user [18]
```
But also, the following statement suggests that the EE is misinterpreting the availability of iron ore in Sport's cargo hold (Sport has 4 u iron ore) and the meaning of Sport's sell order (Sport only wants to keep 1 u iron ore):
```
* 22/04/2020,11:31:10.223 [0] drone [52], has [1] units of resource [1], needs to keep [2], could sell [0]
```
I'll look into this further to see what's going on behind the scenes.

**Comment by darozak** [comment]
@crodnun, I need a little help with this.  I think I found an error in db_e.c and am trying to recompile the code after making a minor change that narrows the search to increment and decrement events:

```
case PREVIOUS_EVENT_BY_RESOURCE_INFO:
                snprintf(query_text,
                    DB_MAX_SQL_QUERY_LEN,
                    "SELECT * "
                    "FROM events "
                    "WHERE drone = %d and resource = %d and installed = %d and locked = %d "
                    "and outcome = %d " // success
                    "and (event_type = 1 or event_type = 2)" // look only for increment and depletion events
                    "and timestamp < '%s' order by timestamp DESC limit 1;",  //
                    event->drone_id, event->resource_id, event->installed, event->locked, OUTCOME_OK, timestamp_buffer);
                break;
```

However, when I run the make command from forth@advolition I get the following compile error:

```
[forth@advolition] # pwd
/home/forth/workspace
[forth@advolition] # make
gcc -std=c99 -Werror -Wall -O2 -I./include -I/usr/include/mysql -D_DEFAULT_SOURCE=1 -DUSE_CUSTOM_EMBED -DUSE_VM -c config.c -o objs/config.o
In file included from ./include/config.h:14:0,
                 from config.c:15:
./include/engine.h:17:10: fatal error: mysql.h: No such file or directory
 #include <mysql.h>
          ^~~~~~~~~
compilation terminated.
Makefile:33: recipe for target 'objs/config.o' failed
make: *** [objs/config.o] Error 1
[forth@advolition] # ^C
[forth@advolition] #
```
Any idea why its unable to find mysql.h?  I never had this problem before.

**Comment by crodnun** [comment]
Hi Dave, 

This happens again before, seems that upgrading packages we have removed again the mysql driver.

This could be solved easily,just running as root user this command, will install it again:

```
apt install libmysqlclient-dev
``` 
This is the second time this happens, we should review how it happens to avoid it... Fernando suffered the same long time ago. I think that at Upwork's room we discussed the same.

Anyways the problem is that doing changes we remove existing packages, dangerous but hope that only affects this part.

Cheers

**Comment by darozak** [comment]
It worked.  Thanks!

**Comment by darozak** [comment]
All fixed, tested, and [committed ](https://github.com/Darwin-River/Ex-Machinis/commit/5b44d7e1db510db0f31f518be108f3ff9be12d7b )for both push and pull actions. Problem was that the search for current resource quantity was not being limited to increment/decrement events.  Furthermore, when looking for most current market order, the search results were not being sorted by time in descending order.
