### ISSUE TITLE
Limit the time the game engine spends one each drone

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#11]
One way to protect the the game engine from being affected by a runaway script is to limit the amount of time it spends processes the code for one drone before moving on to the next.  

This limit should probably be expressed in terms of the number of lines of code it processes before moving to the next drone.  

Whenever the game engine moves onto the next drone it will save the state of the current drone so it can pick up where it left off after it has cycled back through each of the drones.

**Comment by crodnun** [comment]
A new configurable limit is now in place (3 lines as initial value is set). scripts sent by users are split and only 3 lines are processed each cycle. Taste it and let me know if there is something we should change there.

**Comment by darozak** [comment]
I think the line-by-line approach is a good start but not a complete solution.

First of all, I think that we should go word-by-word (characters separated by white spaces) rather than line-by-line (carriage return delimiter) since the former is more consistent with the way the FORTH interpreter processes user commands.  It also accounts for the fact that the processing time shouldn't be effected by the amount of words a user crams on a single line.  But basically this is a good strategy for tracking where the interpreter is in a command string.

However, its not enough to count processor time just by processed words (or even lines).  For example, what if the user had previously defined an long loop in the word, LoopMe.  If the user later calls LoopMe in an email script, the game engine will count that as a single word but the loop invoked by that word will keep the game engine from moving on to process other virtual machines in a timely manner.

A better approach may be to count the number of times to program pointer advances through the compiled program elements in the VM's binary memory.  That way loops and other lengthy processes buried in user-defined words will not be dealt with in terms of the complexity of the underlying routines.  The game engine will process x number of program pointer increments and move on even if the executed command is not complete.

So even though it is important to track the game engines progress in reading and interpreting the email script (tracking words or lines) the game engine must actually limit the time it spends processing a particular program by measuring its progress though the compiled (ie. binary) component of the FORTH code.

**Comment by darozak** [comment]
Closed.  We resolved this issue with the switch to Richard's Embed FORTH.
