### ISSUE TITLE
Allow users to abort a runaway script

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#12]
The users should be able to abort any script that is being run by a done.  This can accomplished by sending the <abort> tag to the drone in an email.  

When the drone sees this email at the beginning of a game engine cycle, it will stop whatever it is doing and send an email to the user confirming that the script has been aborted.

The abort email will also contain a dumpt of any output generated by the aborted script.

**Comment by darozak** [comment]
Here are some more thoughts on the abort command. Basically, the user will send the string "<abort>" to a drone that is processing an endless loop or a runaway script.  When the game engine receives an email that contains <abort> as the first tag in the email chain, it will immediately terminate any ongoing code.  It will then send an email back to the user with any IO text as well as a message indicating that the script has been terminated.

This will be important as users start playing around with complex codes that could generate endless loops.  Do you think this will be hard to implement?

Dave

**Comment by crodnun** [comment]
Hi Dave, could you detail a bit more this new command. A bit confused.

Some doubts:

1) How the script that sends the user looks like?
2) When you say tag, do you mean "abort" tag?
3) Could you write here just a quick example, a user runs this, then aborts, then receives XXX,

Thanks

**Comment by darozak** [comment]
Hi Carlos.  I'll try to give you a clearer example.  Suppose a player writes a FORTH routine that puts his drone into an endless loop.  Right now there is no way for the player to stop this action.  He needs a way of telling the spacecraft to abort whatever code it is currently running.

I think the best way to do this is by allowing the player to email their spacecraft with an abort command.  This needs to be a command that functions outside the FORTH interpreter.  It wouldn't do any good to send something like <script>abort</script> because the interpreter is caught in the middle of an endless loop and won't be listening for new commands.

So rather than sending <script>abort</script>, the player will send <abort> which signifies its a meta-command that functions outside the interpreter.

Right now when the game engine sees something between the <script></script> brackets it sends the contents to the interpreter.  However, when it sees <abort> instead, we want the game engine to terminate whatever code the drone is running.

The game engine also needs to notify the user that the drone successfully terminated the runaway code.  So it will send an email back to the user from the drone that says "Script aborted."

It may also be helpful for troubleshooting purposes if the email contains any text that had accumulated in the IO buffer and would have been been returned to the user at the successful end of the aborted program.  Anther way to think of this is that the <abort> command invokes the "report" command just before stopping the process.  However, if this last part is two hard to accomplish having the drone simply report "Script aborted." would be sufficient.

There may also be other ways to implement an abort routine and I'm open to suggestions.  I hope this is a little clearer.

**Comment by crodnun** [comment]
This feature, at least a beta should be in place in advolition server.  When you send and empty script, we reset VM machine stacks and return an "Script aborted" email. I will need your help to create an infinite loop here and debug the same (this is why I called beta).

At this point, we need now to take into account another old feature that is not integrated yet at this new embed version. To limit the time that each user can use his VM in each cycle.  Richard has added new functions for the same here and we can control when an VM yields or can continue executing more instructions.
The connection is done by means of a callback where we can decide when to stop, for example after X seconds, to avoid a user hogging the game-engine and not allowing other users to use it.

What do you think, I think that both features must go together, does not make sense to use only the abort one, an infinite loop will be running now at the game-engine for ever if you do not send the abort command.

**Comment by darozak** [comment]
I didn't realize that the Game Engine was no longer limiting the length of time it stays with one VM before going to the next.  We need to implement a cycling feature so the game engine only spends a few seconds on one VM before going to the next.  Can you take care of this first?  I'll create a separate issue for that.  In the meantime I'll play around with loops and the abort command to see how well that works.

**Comment by darozak** [comment]
The abort command works to terminate a script.  Issue closed.
