### ISSUE TITLE
Quotes seem to be deleted by the mail handler

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#15]
When I send the following text in the body of an email to one of my drones, the drone executes the code between <script></script> and ignores the other text in the email, as it should.  However, if you look at how the original email is quoted in the response that comes from the drone, you will notice that the quotes are missing from around the word ignored.

START_EMAIL_TEXT

<script> 2 2 + . </script>

This text is "ignored"

STOP_EMAIL_TEXT

The quotes are similarly striped from inside the <script></script> brackets preventing me from using FORTH words like **."** which include a quotation mark in the word.

We need to fix the Mail Handler or Game Engine (I'm not sure where the problem lies) so that it doesn't strip quotation marks from emails.

**Comment by crodnun** [comment]
Detected bug at quotes handling, they were not scaped correctly. Fixed and updated at both servers.
Dave kindly check the same when possible.

**Comment by darozak** [comment]
Hi. I just tested it.  The bug has been fixed and the quotations work beautifully! Its now possible to instruct your drones to include text strings in their email responses (https://www.patreon.com/posts/hello-world-from-21017792).
