### ISSUE TITLE
Create a report command

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#16]
As far as the first FORTH command to create, I suggest we make a simple word, "report", which forces the spacecraft to return the current IO contents in the middle of a program. Right now it waits for the script to start running before sending an email back to the user with the printed results. However, there may be a need to have the drone report results before it finishes processing the script.

**Comment by darozak** [comment]
Carlos wrote:

The feature you requested should be in place now at advolition

it was fast, a pity the delay in reading your messages, sorry

Now when you send this script:

you receive 2 emails,

the problem is how we deal with the report command itself, embed always return an ok for the command executed

you receive these emails:


First operation:


---- Output ----

9 ok

Second operation:

---- Output ----

report ok (this report string is added by me, embed only displays "ok")
5 ok

We can disable the echo at VM config (Richard provides options to do the same, but we lose an important part of the FORTH language)

How you would like to solve this minor issue?

**Comment by crodnun** [comment]
Ok Dave, this change is in place, no more "ok" at output will be displayed. The same option that disables the "ok" also disables the annoying prompt displayed the very first time you run a command in your VM, so we killed to birds with the same stone (I do not know if you use the same expression there :-)).

The same setting disables outputs like this one:

**eFORTH v1984**
**5402 10982**

Check it and let me know your feedback.

**Comment by darozak** [comment]
The new command appears to be working perfectly!  Thanks.  Issue closed.
