### ISSUE TITLE
What happens with emails sent to drone that are actively processing a script?

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#18]
When a user sends an email to a drone that is currently processing another command, the following should happen:

1. The drone responds to the email saying that it is currently processing another script and the current email instructions will not be processed.  The user must resend the code at a later time. 

2. The email discards the new email and doesn't process the code unless it is resent after the current script ends or is aborted by the user.

**Comment by crodnun** [comment]
Now the game-engine discards any command received while processing a previous script, an email with "Another command is running, retry later" message is sent back to the user when this occurs.

**Comment by darozak** [comment]
Works well.  Thanks!
