### ISSUE TITLE
Implement execute function

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#21]
We need to create an execute function that can be called from FORTH by drones to affect the in-game environment.  This function and the associated DB tables are described in the [Game Design Manual](https://docs.google.com/document/d/1FTxA9c4KMpC-rolHbRZXVLejkLHdQtXpdgg7ALDoRoM/edit?usp=sharing).

**Comment by darozak** [comment]
Carlos has begun implementation of the execute command.  To test this I designed a very simple "mine ore" protocol, which places ten units of ore in the drone's cargo hold every time the protocol is executed.

Running the code generated the attached [Execute_function_logs.docx](https://github.com/Darwin-River/Ex-Machinis/files/3317985/Execute_function_logs.docx) to which Carlos appended a number of comments and questions.  He has also raised the following issues with execute routine that need to be addressed:

1. If we purge old events periodically, we could not know the previous quantity. We should keep here "latest event for every resource & drone"

2. Also, I am thinking about how we can report the current drone status at email (it would be a good way to see how the things are going inside the engine), the same way we report the position (light minutes), we could also report the cargo, or other features we consider.

**Comment by darozak** [comment]
Carlos, I've tried to address each of your comments in 
[Execute_function_logs Edited.docx](https://github.com/Darwin-River/Ex-Machinis/files/3318013/Execute_function_logs.Edited.docx). 

I agree that we need to keep the latest event for every resource and drone.  I think the best way to do this might be to purge old events only as new events of the same sort are added.  That way, the game engine will only delete an old event that adds ore to a drone's cargo hold when a new event, which provides a recent tally of the ore, is created.  The same strategy will work for protocols that change a drone's location.  Old location events will be deleted only when a new location event is created, ensuring that we never lose track of a drone's location.

Ultimately, drones will be able to report all aspects of their current status via the query command, which has yet to be implemented.  However, for now, I agree that it might be helpful to have the drone report the amount of materials (in kg or metric tons) that are currently in its cargo hold.

**Comment by darozak** [comment]
I think I've come up with a strategy to keep a running tally of the amount of cargo space that's available to a drone.  My first thought was to simply create a field that holds the current weight of the ship's cargo in the drone table.  However, the events tables are set up in such away that they allow players to review the full history of actions undertaken by their spacecraft.  Cargo size is a data point that should also be traceable over time.  Therefore, it may work better to keep a running tally of the drone's cargo size within the events table itself.  That will allow someone to track how the cargo changes over time.  I'll codify this in the design manual.  Unfortunately, with family visiting over the weekend, I didn't get the time I had hoped for to write this all up.

**Comment by darozak** [comment]
As promised, I've revised the [Game Design Manual](https://docs.google.com/document/d/1KEsBm6P-XXDbSIkt_ML5vXnad3MQXkkPxO6IQ1pDBa8/edit?usp=sharing) to address the each of concerns raised above.  I've used edit marks and comments to highlight these changes, which mainly occur in chapters 5 and 6.

This most significant change is to create an Event Engine for confirming that sufficient resources and cargo space is available at the time of the event.  If not, the Event Engine will log an error and abort the corresponding action.

I've also proposed tracking current resource and cargo values in the events table.  This will ensure that we maintain a searchable record of these values that players can use for trouble shooting purposes.  This strategy will also allow us to easily delete older events, which have exceeded the data expiration date and risk filling the database beyond limits.

Please review the proposed changes and let me know if they provide reasonable solutions to our problems.

Thanks!

**Comment by darozak** [comment]
Here's a bit more information on how the Game and Event Engines will interact via the database.

When the Game Engine responds to an execute command it often initiates a spacecraft action that will take minutes to hours to complete. It does this by defining a series of events that will take place at different points in the future if everything goes as planned. However, it is not known whether these future events will be successful until they actually happen. For example, it might take 10 minutes for a spacecraft to mine ore and for the ore to actually be placed in the ship's cargo hold. However, during that time, the cargo hold might be filled with other materials so that when it is time to place the the ore in the hold, there is no more room and that event (adding units of ore to the spacecraft's hold) fails.

We need the status field because events are created and evaluated at different times and we need to distinguished planned, completed, and failed events from one another. This data is useful not only to the Game Engine but also to players who are troubleshooting errors in their FORTH code.

Since creating and evaluating events are two distinct activities that occur at very different times, I think it makes sense to have them processed by two separate applications. This is consistent with our strategy of having a central DB that is attended to by a range of different applications all running in the background. The Mail Handler deals with incoming and outgoing messages while the Game Engine processes FORTH commands, setting up events in response to calls that are made via the execute command. The Event Engine will evaluate and implement each of these events when it is time for them to actually happen

**Comment by crodnun** [comment]
We have replaced execute -> perform to avoid collision with FORTH's one

now onwards protocols must be executed with this command:

<script>1 1 perform</script>

We have added tons of queries for the events-engine, required to deal with the logic described at Chapter 6. The Event Engine

we are able now to do most of the stuff described there but once I implemented things I realize that:


We do not have entries at hulls table (important to know what are the different types of hulls supported by the game)



Without the hulls, we can not determine what is the max cargo of current drone



I will need your help to understand the observation part, the following points are not implemented yet:


---------------------------------
**_Then, the EE creates a new observations table entry for the acting and affected drones and sets the observation time to that of the event plus the distance in light minutes that the drone is away from the event. For drones that are local to the event (meaning they are orbiting the same static object), the observation time is identical to the event time.
If the event is reportable (i.e. the reportable field is true), then the EE creates an observations table entry for the Central Database (Drone ID = 0) and sets the observation time to the event time plus the distance of the drone from the Earth in light minutes.
If the event is observable and the event does was successfully processed (i.e. the observable field is true and status = 1), the EE also creates observation table entries for each local drone and sets the observation time to the event time._**
----------------------------------------


We are able now to deal with events, at least the mine ore one, and accumulate quantities to update the total cargo, remove old events and keep only one, but I will need some light at observation logic, what is the purpose of this part?

**Comment by darozak** [comment]
So, in addition to determining if a scheduled event actually takes place, the Event Engine must also determine which drones observe the event and at what time they observe the event.  This is because not every drone can see everything that is going on and, if a drone does observe the event, it may be so far away that it takes minutes for the event's signal to reach the drone.  The observation table is used by the Event Engine to record who observes what and when.

When determining which drones observe an event, the Event Engine generally uses the following logic:
- All events are observed by the acting and affected drones.
- Observable events are also observed by any other spacecraft in orbit around the same object.
- Reportable events are also observed by the Earth Based Central Database.

When it comes to determining when a drone will observe an event, the Event Engine applies the following rules:
- A drone orbiting the same object as the affected drone will observe the event when it occurs (observation time = current time).
- A drone orbiting a different object than the affected drone will observe the event at a time determined by its distance in light minutes from the affected drone (observation time = current time + distance in light minutes).
- All reportable events will be observed by the Central Database at a time determined by the affected drone's distance in light minutes from the Earth (observation time = current time + distance in light minutes from Earth).

The Event Engine will create an observation table entry for each drone that observes the event.  The table entry will record the ID of the observing drone, the ID of the event, and the time at which the drone will observe the event.  The Central Database has a drone ID of 0.

Observation table entries will be deleted whenever the corresponding event is deleted by the Event Engine.

**Comment by crodnun** [comment]
Thanks Dave, really nice explanation. Just one doubt here:
The new element "Central database" when it is created? is unique, isn't it? when we should populate/instert this special droneID at database?

**Comment by darozak** [comment]
Drone ID = 0 is just a marker for the Central Database. However, this will have a special meaning when we develop the query command. Basically, any drone will be able to query event data stored in the Central Database but at the cost of a time delay.  This data will be identifiable via observation table entries that link events to Drone ID = 0.

**Comment by crodnun** [comment]
Most of the logic to deal with the observations table is in place (90%) now, we should address the following action points:
- Hull types (important to do the cargo maths)
- DroneID 0, where we configure it?
- What happens next after the event is valid, how we execute it really at FORTH?
- Only one protocol is in place: mine ore, maybe more could be added to test more logic branches
- How we should report all this stuff (to user) now that part of the logic is executed at game engine and the rest at events-engine? Events engine does not have access to user email (for the moment),.

**Comment by darozak** [comment]
Great! I'ill work on creating some basic hull types and additional protocols to use in testing the perform command and Event Engine logic.

Since all cargo and spacecraft location data is stored in the events table, validated events are the endpoints for any spacecraft actions.  In most cases, nothing else needs to be done. 

Nothing needs to be done about the DroneID = 0 either.  That drone doesn't actually exist or function in any manner.  It's simply a mailbox number for generally searchable event data.

Players will learn of all in game events by using a FORTH-based query command to retrieve information from the database. Therefore the next step will be to develop the query command as described in Chapter 7 of the [Game Design Manual.](https://docs.google.com/document/d/1FTxA9c4KMpC-rolHbRZXVLejkLHdQtXpdgg7ALDoRoM/edit?usp=sharing)

When you have a chance.  Please review the proposed logic for the query command and let me know if you have any questions.  I've created a separate Issue for [developing the query command](https://github.com/Darwin-River/Ex-Machinis/issues/25).  Please post related questions there.

**Comment by darozak** [comment]
I'm going to create separate issues for each of the above observations so that we can track their solutions separately along with any other bugs or improvements we identify with the **perform** command.  In the meantime, I'll close out this particular issue as having successfully established the core mechanics for the **perform** function.
