### ISSUE TITLE
The process multiplier doesn't appear to work with the perform command

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#27]
The **perform** command is supposed to pull at least two values from the stack. The first value is the protocol number and the second is the process multiplier, which indicates the number of times that the protocol is performed in a row. The perform routine correctly uses the protocol number to distinguish between two protocols that I placed in the DB (1: mine iron ore and 2: mine carbon ore). However, it doesn't appear to matter whether I use a process multiplier of 1 or 2. In both cases it adds the same amount of ore to the cargo hold when it should be adding one or two times that amount depending on the process multiplier.

**Comment by crodnun** [comment]
You are right, it was not considered yet. Now in place.
To be tested at Dave's side before closing the issue

**Comment by darozak** [comment]
I tested the process multiplier and at appears to work fine.  Thanks for fixing this.
