### ISSUE TITLE
Must delete irrelevant observation table entires

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#29]
When an event is deleted from the Central DB because the event has exceeded its lifespan (or for any other reason) any observation table entries that point to that event should also be deleted.

**Comment by crodnun** [comment]
Added on cascade statement at table definition to delete them automatically

**Comment by darozak** [comment]
The Event Engine no longer appears to be recording observations.  Despite performing multiple protocols to add and remove ore from a drone's cargo hold there only appears to be one observation recorded in the observations table (Observation ID = 16).  The way the protocols are currently configured with both protocols.observable and protocols.reportable fields set to 1 for all protocols, each event should generate observation table entries for the Common DB (Object ID = 1), the drone that was directly affected by the event, and any drones that are orbiting the same object as the affected drone.

**Comment by crodnun** [comment]
Should be fixed now, I messed it up with the foreign key added there to delete on cascade, the latest insertions were failing due to this error

**Comment by darozak** [comment]
It's working! Except you appear to be recording a second entry for the affected drone rather than an entry for the Common DB.  In the attached screenshot, each of two of the three recorded observation entries reference the affected drone while he third references a drone in the same orbit.  However, there aren't any entries for DroneID = 0.  I also may have steered you wr
![Capture](https://user-images.githubusercontent.com/33500329/65379904-27ab6c00-dc9e-11e9-96d2-4b5b3c2260f7.PNG)
ong in the earlier comment where I incorrectly said that the DroneID for the Common DB is 1.  It should be 0.

**Comment by crodnun** [comment]
OK, should be fixed  now (double check if this is the behaviour you expect). Now we insert observations for:
1) Current object
2) Other objects at the same position
3) Central Database with drone ID = 0

**Comment by darozak** [comment]
This appears to be working nicely now.  Thank you.
