### ISSUE TITLE
Depletion events add rather than remove resources from the cargo hold

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#30]
I created a protocol (number 4) which is supposed to remove (depletion event) one unit of iron ore from the drone's cargo hold.  However, when I perform this event, it appears to **add** one unit of ore to the cargo hold rather than depleting it.

**Comment by crodnun** [comment]
Fixed now, after reviewing the unsigned fields at DB and using the right type when dealing with quantities.
Now this protocol should work removing 1 unit as expected.
Also tested with multipliers.

To be tested by Dave before closing the issue.

**Comment by darozak** [comment]
Tested.  Works perfectly.  Thanks!
