### ISSUE TITLE
We need to assign a hull type to each drone when they are created

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#31]
Drones are created by email (at registering), so we need to implement some kind of logic there to ensure that each drone has a valid hull type since the beginning.
Some kind of logic at email/PHP side is needed to generate this information.
Hull type is important to work with protocols later.

**Comment by darozak** [comment]
Every new drone should be assigned a hull type of 1.

**Comment by crodnun** [comment]
Done, now when registering, the drones created for each user recieve the default hull type agreed: 1

I have removed users from DB and created my drones from scratch and this what we obtain now:

mysql> select agent_id, user_id, name, hull_type from agents;
+----------+---------+----------+-----------+
| agent_id | user_id | name     | hull_type |
+----------+---------+----------+-----------+
|        1 |       1 | SN652755 |         1 |
|        2 |       1 | SN678077 |         1 |
|        3 |       1 | SN390039 |         1 |
+----------+---------+----------+-----------+

Feel free to test this feature at advolition, you should have to register again your drones (they were removed).
