### ISSUE TITLE
Wrong DB field definition, type must be changed for outcome

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#32]
We have now at DB the following definition for events table:

```
mysql> desc events;
+------------------+------------------+------+-----+-------------------+----------------+
| Field            | Type             | Null | Key | Default           | Extra          |
+------------------+------------------+------+-----+-------------------+----------------+
| id               | int(10) unsigned | NO   | PRI | NULL              | auto_increment |
| event_type       | int(2) unsigned  | YES  |     | NULL              |                |
| action           | int(10) unsigned | YES  | MUL | NULL              |                |
| logged           | tinyint(4)       | YES  |     | NULL              |                |
| outcome          | int(2) unsigned  | YES  |     | NULL              |                |
| drone            | int(10) unsigned | YES  | MUL | NULL              |                |
| resource         | int(10) unsigned | YES  |     | NULL              |                |
| installed        | tinyint(4)       | YES  |     | NULL              |                |
| locked           | tinyint(4)       | YES  |     | NULL              |                |
| new_quantity     | int(10) unsigned | YES  |     | NULL              |                |
| new_credits      | int(10) unsigned | YES  |     | NULL              |                |
| new_location     | int(10) unsigned | YES  |     | NULL              |                |
| new_transmission | int(10) unsigned | YES  |     | NULL              |                |
| new_cargo        | int(10) unsigned | YES  |     | NULL              |                |
| timestamp        | datetime         | YES  | MUL | CURRENT_TIMESTAMP |                |
+------------------+------------------+------+-----+-------------------+----------------+
15 rows in set (0.00 sec)
```
Notice that we are using outcome as unsigned, but at design document we can assign negative values (0, -1, -2, -3, etc),  Chapter 6 - Events engine.

When we display the values present in DB, we do not identify clearly the negative codes, they are truncated to unsigned values (253, 254, etc,...):

mysql> select * from events;
+----+------------+--------+--------+---------+-------+----------+-----------+--------+--------------+-------------+--------------+------------------+-----------+---------------------+
| id | event_type | action | logged | outcome | drone | resource | installed | locked | new_quantity | new_credits | new_location | new_transmission | new_cargo | timestamp           |
+----+------------+--------+--------+---------+-------+----------+-----------+--------+--------------+-------------+--------------+------------------+-----------+---------------------+
| 35 |          1 |     62 |      1 |     **253** |     7 |        3 |         0 |      0 |            0 |           0 |            0 |                0 |        30 | 2019-09-12 17:09:40 |
| 37 |          1 |     64 |      1 |     **253** |     7 |        1 |         0 |      0 |            0 |           0 |            0 |                0 |        50 | 2019-09-12 17:14:11 |
| 40 |          1 |     67 |      1 |       1 |    11 |        3 |         0 |      0 |            0 |           0 |            0 |                0 |        30 | 2019-09-13 00:47:12 |
| 43 |          1 |     70 |      1 |      **253**  |    11 |        1 |         0 |      0 |            0 |           0 |            0 |                0 |        60 | 2019-09-13 00:51:33 |
| 44 |          2 |     71 |      1 |      **253**  |     7 |        1 |         0 |      0 |            0 |           0 |            0 |                0 |        51 | 2019-09-13 17:33:43 |
| 51 |          1 |     78 |      1 |      **253**  |     1 |        1 |         0 |      0 |            0 |           0 |            0 |                0 |        70 | 2019-09-17 06:21:42 |
+----+------------+--------+--------+---------+-------+----------+-----------+--------+--------------+-------------+--------------+------------------+-----------+---------------------+
6 rows in set (0.00 sec)

**Comment by darozak** [comment]
I agree that the field should allow unsigned integers.

**Comment by crodnun** [comment]
Changed done, to be tested by Dave before closing the issue.

**Comment by darozak** [comment]
Working nicely.
