### ISSUE TITLE
Do we have the right values at this table?

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#33]
At resource effects, for deplete flag we use -1 or 0 values right now. But design documentation says that we should have true or false. is -1 value considered a true here? We are not treating this field properly because the -1 is considered a false too :-).

mysql> select * from resource_effects ;
+----+-------+----------+----------+------------+-------+-----------+--------+---------+----------+------+
| id | drone | resource | protocol | event_type | local | installed | locked | deplete | quantity | time |
+----+-------+----------+----------+------------+-------+-----------+--------+---------+----------+------+
|  1 |     0 |        1 |        1 |          1 |    -1 |         0 |      0 |       0 |       10 |    0 |
|  2 |     0 |        3 |        2 |          1 |     0 |         0 |      0 |       0 |       10 |    0 |
|  3 |     0 |        1 |        3 |          2 |     0 |         0 |      0 |      -1 |        1 |    0 |
|  4 |     0 |        2 |        3 |          1 |     0 |         0 |      0 |       0 |        1 |   10 |
|  5 |     0 |        1 |        4 |          2 |     0 |         0 |      0 |      -1 |        1 |    0 |
+----+-------+----------+----------+------------+-------+-----------+--------+---------+----------+------+
5 rows in set (0.00 sec)

**Comment by darozak** [comment]
I've been entering this data via an MS Access front end.  It appears that Access enters a -1 in this filed if the checkbox is checked (i.e. true).  Unchecked boxes (i.e. false) register a 0 in the corresponding DB field.  FORTH also appears to treat -1 and any other non zero value (including 1) as true and 0 as false. I'm not sure if this is a standard convention.  Does this present a problem if we treat 0 as false and -1 as true?  Alternatively, does SQL allow us to declare Boolean fields?

**Comment by crodnun** [comment]
Hi Dave, Mysql does not have a boolean type so far.
In recent versions the have added a new constraint statement:  CHECK IN(A,B) that allows us to ensure that a value is within the range we expect. Unfortunately, our current version does not have it yet.
The decision I have taken is to force it to be a tinyint(1) unsigned NOT NULL DEFAULT(0), this way we always have positive values there: 0, 1, 2, 3,, ...
I am with you that -1 could be considered as true (anything different from 0 is true), but as human, is easier to understand when you look at DB if you find 0's and 1's. I have done the changes at DB to accommodate the same as follows:

mysql> desc resource_effects;
+------------+---------------------+------+-----+---------+-------+
| Field      | Type                | Null | Key | Default | Extra |
+------------+---------------------+------+-----+---------+-------+
| id         | int(5) unsigned     | NO   | PRI | NULL    |       |
| drone      | int(5) unsigned     | YES  |     | NULL    |       |
| resource   | int(5) unsigned     | YES  |     | NULL    |       |
| protocol   | int(5) unsigned     | YES  | MUL | NULL    |       |
| event_type | int(2) unsigned     | YES  |     | NULL    |       |
| local      | tinyint(1) unsigned | NO   |     | 0       |       |
| installed  | tinyint(1) unsigned | NO   |     | 0       |       |
| locked     | tinyint(1) unsigned | NO   |     | 0       |       |
| deplete    | tinyint(1) unsigned | NO   |     | 0       |       |
| quantity   | int(5) unsigned     | YES  |     | NULL    |       |
| time       | int(5) unsigned     | YES  |     | NULL    |       |
+------------+---------------------+------+-----+---------+-------+

And also updated current DB content to meet this criteria:

mysql> select * from resource_effects;
+----+-------+----------+----------+------------+-------+-----------+--------+---------+----------+------+
| id | drone | resource | protocol | event_type | local | installed | locked | deplete | quantity | time |
+----+-------+----------+----------+------------+-------+-----------+--------+---------+----------+------+
|  1 |     0 |        1 |        1 |          1 |     1 |         0 |      0 |       0 |       10 |    0 |
|  2 |     0 |        3 |        2 |          1 |     0 |         0 |      0 |       0 |       10 |    0 |
|  3 |     0 |        1 |        3 |          2 |     0 |         0 |      0 |       1 |        1 |    0 |
|  4 |     0 |        2 |        3 |          1 |     0 |         0 |      0 |       0 |        1 |   10 |
|  5 |     0 |        1 |        4 |          2 |     0 |         0 |      0 |       1 |        1 |    0 |
+----+-------+----------+----------+------------+-------+-----------+--------+---------+----------+------+

Everything is also pushed into repository at Mysql Workbench stuff we store there.

**Comment by darozak** [comment]
Ok.  That makes sense.  We'll go with 0 and 1 for false and true.
