### ISSUE TITLE
Changes in data types required to allow depletion of resources easily

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#34]
At events table, we deal always with positive quantities and there is no way to indicate that these amounts are depletion quantities.

For  events engine, this implies that it has to search the associated action, then the associated protocol and then the deplete flag value to guess if it is a positive or negative amount.

I think that changed the quantities fields types to int (instead of unsigned int) we could avoid tons of queries at events engine.

The game engine would insert the quantity change positive/negative and the events engine just needs to do the maths using them, no need to launch many queries to guess it.

Current table definition is:

mysql> desc events;
+------------------+------------------+------+-----+-------------------+----------------+
| Field            | Type             | Null | Key | Default           | Extra          |
+------------------+------------------+------+-----+-------------------+----------------+
| id               | int(10) unsigned | NO   | PRI | NULL              | auto_increment |
| event_type       | int(2) unsigned  | YES  |     | NULL              |                |
| action           | int(10) unsigned | YES  | MUL | NULL              |                |
| logged           | tinyint(4)       | YES  |     | NULL              |                |
| outcome          | int(2) unsigned  | YES  |     | NULL              |                |
| drone            | int(10) unsigned | YES  | MUL | NULL              |                |
| resource         | int(10) unsigned | YES  |     | NULL              |                |
| installed        | tinyint(4)       | YES  |     | NULL              |                |
| locked           | tinyint(4)       | YES  |     | NULL              |                |
| new_quantity     | int(10) unsigned | YES  |     | NULL              |                |
| new_credits      | int(10) unsigned | YES  |     | NULL              |                |
| new_location     | int(10) unsigned | YES  |     | NULL              |                |
| new_transmission | int(10) unsigned | YES  |     | NULL              |                |
| new_cargo        | int(10) unsigned | YES  |     | NULL              |                |
| timestamp        | datetime         | YES  | MUL | CURRENT_TIMESTAMP |                |
+------------------+------------------+------+-----+-------------------+----------------+

but we could move some of them to int(10), removing the unsigned restriction.

what do you think Dave?

**Comment by darozak** [comment]
Thanks Carlos.  I totally agree. These values should be signed integers and changes given as positive or negative values.

**Comment by crodnun** [comment]
OK done, at latest changes pushed to the repository.
advolition.com environment updated with these changes.
