### ISSUE TITLE
Purpose of the field "internal" within the protocols table

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#36]
What's is the purpose of this field:

CREATE TABLE IF NOT EXISTS `exmachinis`.`protocols` (
  `id` INT(5) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `parameters` SMALLINT(2) NOT NULL DEFAULT 0,
  `bulk_modifier` INT(5) UNSIGNED NULL,
  `description` VARCHAR(255) NULL,
  `observable` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `reportable` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  **`internal` TINYINT UNSIGNED NOT NULL DEFAULT 0,**
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

**Comment by darozak** [comment]
That must be a legacy field that we don't use anymore.  It can be deleted.

**Comment by crodnun** [comment]
OK, updated everywhere: DB model, DB creation script and advolition server database (no longer present)
