### ISSUE TITLE
Email handler no longer working at old URL

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#37]
Trying to test the latest changes, the email handler seems no longer available,  now we have an HTML page instead of the email handling system.

This URL:  https://advolition.com/   was used internally by the email handler to process emails but seems broken now.

If we want to use it for HTML code, we should move the email handler system to a new address as Fernando suggested.

**Comment by darozak** [comment]
Sorry about that!  I fixed it.
