### ISSUE TITLE
Allow the Event Engine to track changes in spacecraft location

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#39]
We need to expand the capabilities of the Game and Event Engines so that they can process actions that involve a change in a spacecraft's location.  These are described in the location_effects table and the new location is tracked in the events table.  Eventually, the Game Engine will need to compute the time and resources that are required for a ship to travel greater distances.  However, for now, the Game Engine simply needs to create an event which moves the spacecraft to the specified location in the location_effects table.  The Game Engine should also be able to pull a location ID off the stack and use that if indicate by a negative value in the location_effects.location field.

**Comment by crodnun** [comment]
I have started to push this, at least try :-). Let me know if these changes in current tables would be correct to accommodate this feature:

I have added a new protocol event_type 3:

```
mysql> select * from event_types;
+----+---------------------+
| id | name                |
+----+---------------------+
|  1 | Increment Inventory |
|  2 | Decrement Inventory |
**|  3 | Move to location    |**
+----+---------------------+
```

I have added a new protocol to invoke it with the perform command:

```
mysql> select * from protocols;
+----+-----------------+------------+---------------+------------------------------------------------------------------+------------+------------+
| id | name            | parameters | bulk_modifier | description                                                      | observable | reportable |
+----+-----------------+------------+---------------+------------------------------------------------------------------+------------+------------+
|  1 | Mine Iron Ore   |          0 |           100 | This protocol is used to add iron ore to your ship's cargo hold. |          1 |          1 |
|  2 | Mine carbon ore |          0 |           100 | This protocol adds carbon ore to your inventory.                 |          1 |          1 |
|  3 | Smelt iron ore  |          0 |           100 | This protocol converts iron ore to iron pellets.                 |          1 |          1 |
|  4 | Dump Iron Ore   |          0 |           100 | Dumps a unit of iron ore from the cargo hold.                    |          1 |          1 |
**|  5 | Move to X       |          0 |           100 | Initial draft for location effects                               |          1 |          1 |**
+----+-----------------+------------+---------------+------------------------------------------------------------------+------------+------------+
```
And finally I have added the kind of initial/dummy version for a location_effect:

```
mysql> select * from location_effects;
+----+----------+------------+----------+------+
| id | protocol | event_type | location | time |
+----+----------+------------+----------+------+
|  1 |        5 |          3 |        -1 |    0 |
+----+----------+------------+----------+------+
```

My goal here is to move to the requested object ID (user provides the same using the stack):

Example:

**<script>1 5 perform</script>**

With this command we would move to object ID = 1 (Mercury at our DB)

Let me know your thoughts regarding the same, to fix or go ahead with current data.

**Comment by darozak** [comment]
The new DB entries look perfect. This is exactly how I would have constructed the test protocol.

**Comment by crodnun** [comment]
I have struggled a bit with these new effects, and have some doubts regarding the tables and how they should work.

So far we have the following syntax for mining effects:

<script>1 2 perform</script>

Where we retrieve from the stack: the protocol (2) and the multiplier (1)

But with the location effects, we should follow the same policy, we are using the same "perform" command so we should use the same syntax here.

We can not sometimes invoke:

<s>1 2 perform</s> where 2 is a protocol to move and 1 is the object we move to

and others:

<s>2 perform</s> where we move to the configured effect object (present at DB)

I think that for both should use the protocol value: the number of parameters and this way determines how many stack values we receive after protocol ID.

This way the general syntax for the perform command would be:

<number of parameters for this protocol>  <protocol> <perform>

Right now for the resource effects we need the multiplier, but for location, it does not make sense to use it here.

What do you think we should create a generic format for all them.

**Comment by darozak** [comment]
This is a good point.  I agree that we should come up with a standard format for the perform command and that the multiplier isn't required in every case.  In fact, the multiplier parameter will not be required for the market effects table either.  

I suggest we stop pulling the multiplier value from the stack and automatically set it to 1.   The only required parameter for the perform function will be the protocol number.  This will be the first value pulled off the stack.  However,  some protocols will pull additional values from the stack based on the the configuration of the effects tables.

**Comment by crodnun** [comment]
What about passing the multiplier to protocols params? Perform will receive a single stack value. The protocol Id and the rest will depend on protocol's parameters. Makes it sense. Do we cover this way all the scenarios you have in mind?

**Comment by crodnun** [comment]
I have added an improvement here (before moving to location effects) in order to have a uniform format for the perform command.

I have added a new flag at the protocols table with name **multiplier**:

```
CREATE TABLE IF NOT EXISTS `exmachinis`.`protocols` (
  `id` INT(5) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `parameters` SMALLINT(2) NOT NULL DEFAULT 0,
  `bulk_modifier` INT(5) UNSIGNED NULL,
  `description` VARCHAR(255) NULL,
  `observable` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `reportable` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `multiplier` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;
```

It is just a flag (0/1) to indicate (when enabled) that this protocol can receive an optional multiplier at the end of the list of expected parameters (given by the parameters field).
This way for our 'mine XX' protocols we set it to 1 and we check if the user has provided this multiplier value at stack to use it, otherwise the engine applies default value of 1.

If we run:
<script>1 perform</script>    we mine 10 units of Iron (engine applies default multiplier 1)
<script>10 1 perform </script> we mine 10 * 10 units of iron (we use the user's supplied multiplier)

I think that with this flag we have a more uniform treatment for the protocols table and the perform command. The multiplier flag, when enabled, will indicate that the user can provide an optional multiplier value at the end of the expected parameters numbers, but it is optional, if not found we go ahead with the 1 value.
Let me know what do you think regarding this breaking change, lol.

**Comment by darozak** [comment]
The multiplier flag is a very nice solution!  Thanks for implementing this.

**Comment by crodnun** [comment]
For location effects management I have added the following entries at DB:

At protocols, 2 entries, one protocol to move to the desired location (defined by user's stack parameter), other to move to a specific location (final location is defined by DB):

'''
+----+-----------------+------------+---------------+------------------------------------------------------------------+------------+------------+------------+
| id | name            | parameters | bulk_modifier | description                                                      | observable | reportable | multiplier |
+----+-----------------+------------+---------------+------------------------------------------------------------------+------------+------------+------------+
|  5 | Move to X       |          0 |           100 | Initial draft for location effects                               |          1 |          1 |          0 |
|  6 | Move to Jupiter |          0 |           100 | We move without parameters, effect defines destiny               |          1 |          1 |          0 |
+----+-----------------+------------+---------------+------------------------------------------------------------------+------------+------------+------------+
'''

At location_effects table we have now:

'''
mysql> select * from location_effects;
+----+----------+------------+----------+------+
| id | protocol | event_type | location | time |
+----+----------+------------+----------+------+
|  1 |        5 |          3 |       -1 |    0 |
|  2 |        6 |          3 |        5 |    0 |
+----+----------+------------+----------+------+
'''

If we execute:
**<script>6 perform</script>**  User is moved directly to Jupiter. A new event should be inserted to indicate the new location
If we execute:
**<script>1 5 perform</script>** User selects with a parameter the final location, again, a new event should indicate this condition.

Feel free to play around at advolition and let me know your thoughts.

**Comment by darozak** [comment]
Thanks Carlos! This is working very nicely. Everything appears to be updating in the database as it should.  However, I notice that the location and distance reported in the email doesn't change even though the spacecraft has moved.  Where is it getting this location data from?

**Comment by crodnun** [comment]
Yikes!!! this is not updated ... It was so simple the approach that we do not consider it yet. Do you mean to also move the drone there, isn't it?
I just did the events part, but not the 'real life' part, lol. I will update it soon

**Comment by darozak** [comment]
Awesome!  In this game events are reality! But it probably makes sense to also keep track of the drone's location in a more easily accessible field, like where the email is pulling the location from.

**Comment by crodnun** [comment]
Implemented! Now apart from generating events with current location, we also update this value at agents table (the drone is now moved to this location) and this new value is used to fill the data used at the response's email. The answer we receive after executing statements like these:

<script>X 5</script>   ----------------- move to object X

or

<script>6</script>    ------------------ move to jupiter

will always contain the new position and distances.

Example:

```
---- Position ----

At: Oberon
Distance: 152.534817 light-minutes

---- Output ----

Protocol "Move to X" succesfully executed

From: crodnun@yahoo.es
Sent: Sat Oct  5 07:31:23 2019
To: SN678077@advolition.com
Subject: Moving to another place

<script>144 5 perform</script>
```



Kindly review it.

**Comment by darozak** [comment]
Yes!! Works very nicely. Thanks!
