### ISSUE TITLE
Copy user emails in responses from drones

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#4]
When a drone responds to a user's FORTH script, it should reply with an email that (1) uses the original subject (i.e. "RE: Asking my drone to do simple math") and (2) quotes the text from previous emails at the bottom of the outgoing email.   This will help the user track the commands and responses he sends to and receives from a particular drone.

**Comment by darozak** [comment]
I believe this will will require us to make a separate table to hold incoming email data so that it can be used in quoting back subject and content to the sender.  Right now, I don't think this information is being captured.

**Comment by darozak** [comment]
This will be a very helpful improvement when it comes to troubleshooting the FORTH code since the email response will contain both the script and the output.

**Comment by crodnun** [comment]
A solution is in place now for this enhancement. It works as follows;

1) The incoming email is parsed by the email_handler module (PHP codes), and the subject + email content=script=code + agent_id are stored in the commands table.

2) The game_engine reads entries from commands table continously, and also retrieves now the subject to answer the input email.

3) Once read, it stores in agent table the latest input + subject.

4) Executes the command in VM and deletes the entry from commands table.

5) When the output is generated, the game_engine uses this output + current subject + current input to build the answer.

Check it at your side and feel free to share your feedback regarding the same.

**Comment by darozak** [comment]
Hi Carlos.  I  like what you've done!  I think you're on the right track with this.  However, I think its important that the drone capture and propagate the entire email chain.  I've created an example in Google Docs to illustrate what I'm thinking about:

https://docs.google.com/document/d/1hjaS_bBVi8GqCe3vlvflJ5Igog0TkOYzoblfv6QUvIk/edit?usp=sharing

**Comment by crodnun** [comment]
Now the entire email chain should be included in response, also any scaped character is treated now correctly and inserted in DB. Let me know if further adjustements are required at this issue.

**Comment by darozak** [comment]
I tested it out and the system appears to be doing a great job quoting previous emails in the chain and handling escaped characters!
