### ISSUE TITLE
Doubt regarding observations time

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#40]
Hi Dave,
I have a doubt regarding the time to insert at observations table.

We now insert 3 entries when an event occurs:

1- Current drone observation
2- Observations for those drones at the same object
3- Central Database observation

The observation time for 1 is current time,
The same happens for the drones orbiting at the same object,
And for the central database, this value will depend on the object the drone is orbiting, its distance to Earth (I assume here that central database is at Earth object), is this correct?

**Comment by darozak** [comment]
Yes. That's correct.
