### ISSUE TITLE
We'll need a <reset> command

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#41]
Last year we created an <abort> command, which works outside of the <script></script> brackets to automatically abort a runaway script.  However, the abort command doesn't do anything to remedy a corrupt VM, which can result from a user carelessly changing or overwriting portions of the VM.  Therefore, we also need to create a <reset> command which similarly works outside the <script></script> brackets to terminate a runaway routine.  However, the <reset> command will also erase the existing VM and reset it to the configuration that exists for a new drone.

**Comment by crodnun** [comment]
Reset command is in place now. We stop any running command (like abort does) and clean current user's VM, it is set a NULL at DB. Next command sent by the user will start with a fresh VM, no words defined there, just the default VM we assign when the user enters the system for the first time

**Comment by darozak** [comment]
Works!  Thanks!
