### ISSUE TITLE
Allow players to rename their drones

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#42]
Currently, each spacecraft is assigned a random ID (eg. SN012732), which serves as the email address used in player/drone communications. However, this name is not easy to remember.  Ideally, players should be able to reset the name of their drone to something that is more meaningful to them.

I propose creating a rename meta-command, which will be used outside the <script></script> and independent of the FORTH interpreter, to assign a new name to the drone.  

The user will place the case-insensitive command,  '<droneid = "newname">' in the body of an email to the drone whose name they want to change.  This will only work for player-owned drones.

When receiving this command, the mail handler (or game engine?) will change the drone ID to the newname if:

1. newname doesn't contain any characters that are prohibited (eg. @ and space) in an email username, and

2. the case-insensitive newname is not in use by another drone.

The user will then receive a followup email from the drone indicating that the name was successfully changed or that the change was not implemented because the proposed name contains illegal characters or is already in use.

**Comment by crodnun** [comment]
Hi Dave, thinking a bit about the new meta-commands you want to introduce, many questions arise and from my point of view, a way of dealing with this new world of "meta-commands" is required here now.  

We can not define them on the fly, each one with a made-up format, this is not portable and of course leads us to code ad-hoc routines for each one. 

Said this,  I envisage that we will need to generate a format for all them and answer the following questions:

1) How the meta-commands will be sent to the system? Of course by email, lol, but do we need to use a separate email for them or can be sent with an <script></script> block?

2) If we can send them together (meta and script), how we can identify each part? If not (only meta or script emails, never together), how we could model the metadata to parse them easily?

3) Could we have more than 1 meta-command at the same time? It is soon to say this, but maybe in the future, it could happen,...

So far, and including the new ones added, we have the following meta-commands:

<abort>
<droneid="newname">
<reset>

Thinking about the questions I detailed above, I think that a good way to deal with this is:

1) Identify clearly where we have a meta section, using some kind of 
<meta>Put here your meta commands</meta>

2) Then inside the meta section, define (uniformly) the meta-commands, below just my simple proposal:

<meta>

<command>
<name>abort</name>
</command>

<command>
<name>rename_drone</name>
<param>MyBestDrone</param>
</command>

<command>
<name>reset_vm</name>
</command>

</meta>

The idea behind my comments here is just to identify clearly the usage of meta-commands inside the system and of course deal with them uniformly, creating a set of meta-commands that all them work the same way. Some can receive parameters, some do not require them, but we need to be prepared to deal with them somehow at the same time we execute commands inside the VM.

Let me know your thoughts regarding my comments.

**Comment by darozak** [comment]
These are all very good points.  Let me give this some thought.  We need to consider the full range of functions that could eventually be assigned as meta-commands and come up with a simple syntax, which nicely ties them all together.

**Comment by darozak** [comment]
Hi Carlos.  I think we need to keep meta-commands simple so they don't overly complicate the process of communicating with a spacecraft.  Also, I don't anticipate the need for many meta-commands.  Given this limited vocabulary, I can't imagine the player ever needing to invoke more than one command at a time.

I added a short chapter to the design manual that deals with meta-commands.  I've also copied it here.  Please take a look and let me know what you think.

> Players generally interact with their spacecraft via email.  Each spacecraft has its own email address and players use this address to send their drones meta-commands.  Meta-commands are always bracketed by greater than and less than signs (ie. “\<command>”) to distinguish them from other email content, which is ignored by the drones. Most meta-commands enclose a single parameter, which is being sent to the spacecraft.  In this case, the meta-command would be rendered as “\<command> parameter \</command>.”  Spacecraft will only execute the first recognizable meta-command in an email.
>
> Spacecraft recognize a few basic meta-commands, which allow players to execute FORTH scripts, reset errant code, and reconfigure user settings.  These commands are as follows:
> * \<run> parameter \</run> tells the drone to execute the FORTH script contained within the parameter string.  This parameter can contain line breaks and other special characters.
> * \<abort> forces the drone to immediately stop any script that it is currently running and return control to the player.  The drone will return an email confirming that it has aborted the script.
> * \<reset> stops the currently running script and resets the drone’s virtual memory to its factory setting, erasing any code that the player may have entered.  The drone will return an email to confirm that it has successfully reset its memory.
> * \<rename> parameter \</rename> changes the email address of the drone to parameter@exmachinis.com.  Consequently, the parameter must not contain characters that generate an invalid email address and cannot be in use by any other drone or player.  The drone will return an email confirming its name change.  It will also report any failure to change the name and the reason why the proposed name is unacceptable.
> * \<rebrand> parameter \</rebrand> changes the name of the player’s company.  The chosen name must be unique and not exceed the maximum lengths prescribed by the SQL field. The drone will return an email confirming the company’s name change.  It will also report any failure to change the name and the reason why the proposed name is unacceptable.

I propose replacing \<script> with \<run> so all the meta-commands are verbs.

**Comment by crodnun** [comment]
Added initial changes to replace <script> by <run>.

Now onwards, to execute a command inside the VM, we will need to enclose it between the new tags.

Example:

<run>1 2 + . </run>

The old tag <script> is no longer available and will be ignored by the system

**Comment by crodnun** [comment]
All the new meta-commands are in place. Ready to play around ;-) and detect any issue!!!

**Comment by darozak** [comment]
Awesome!  I'll go ahead and play test each of these features and create new issues if I find anything wrong.
