### ISSUE TITLE
Tracking the resource abundancies of orbital objects

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#43]
Currently, mining activities are not constrained by location.  For example, a drone mines the same amount of iron ore no matter where it's located in the solar system.  

However, we really need to have the output of mining (and other resource harvesting) depend on where the drone is located at the time the activity takes place.

To do this, we'll create an abundancies table which associates a multiplier with a particular location and resource.  When a drone tries to harvest a specific resource in a specific location, the amount of the resource that it acquires will be adjusted using the corresponding abundancies.multiplier value. 

The [abundancies table](https://docs.google.com/document/d/1FTxA9c4KMpC-rolHbRZXVLejkLHdQtXpdgg7ALDoRoM/edit#heading=h.v6e3qh83ejn6) and [Event Engine](https://docs.google.com/document/d/1FTxA9c4KMpC-rolHbRZXVLejkLHdQtXpdgg7ALDoRoM/edit#heading=h.pqfmpcw1d20e) algorithm are described in the latest version of the [Design Manual](https://docs.google.com/document/d/1FTxA9c4KMpC-rolHbRZXVLejkLHdQtXpdgg7ALDoRoM/edit?usp=sharing).

In order to implement this enhancement, we'll need to create the SQL abundancies table, populate it with test values for a particular set of resources and location, and code the abundancies logic that is described in the Event Engine section of the Design Manual.

**Comment by crodnun** [comment]
Hi Dave,

New table abundancies added, notice that we need slight changes at your initial model to meet the existing foreign keys present at other tables (resources and objects respectively).

The definition is as follows:

```
-- -----------------------------------------------------
-- Table `exmachinis`.`abundancies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exmachinis`.`abundancies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` INT(5) NOT NULL,
  `resource` INT(10) UNSIGNED NULL,
  `multiplier` INT(2) NULL,
  PRIMARY KEY (`id`),
  INDEX `location_id_foreign_idx` (`location` ASC),
  INDEX `resource_id_foreign_idx` (`resource` ASC),
  INDEX `location_resource_idx` (`location` ASC, `resource` ASC),
  CONSTRAINT `location_id_foreign`
    FOREIGN KEY (`location`)
    REFERENCES `exmachinis`.`objects` (`object_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `resource_id_foreign`
    FOREIGN KEY (`resource`)
    REFERENCES `exmachinis`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
```

I have updated the Mysql stuff at the repository (DB creation script and DB model), and also provisioned this table at advolition server with a single entry for my tests, we can only harvest ore at Earth location (just for my tests, feel free to add or suggest new entries there).

Event engine logic is also updated to support this new table. Feel free to play around with this new feature.

Current table content is:

```
mysql> select * from abundancies;
+----+----------+----------+------------+
| id | location | resource | multiplier |
+----+----------+----------+------------+
|  1 |        3 |        1 |          1 |
+----+----------+----------+------------+
1 row in set (0.00 sec)
```
Test it and let me know your results or bugs detected.

**Comment by darozak** [comment]
This is awesome!  I actually had to fly my drone to a new location to mine a resource.  Everything appears to be working correctly.  I'll play around with this some more but will create a new issue if I find any bugs.
