### ISSUE TITLE
Rename doesn't appear to check for illegal characters

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#44]
I was as able to rename my spacecraft to "a@b" and didn't receive an error or confirmation.  When I checked the database, "a@b" was stored as the drone ID.  We need to make sure the player doesn't request a name that creates an invalid email address.

**Comment by crodnun** [comment]
My fault here, I completely forgot to add validations :-). 
Validations added: 
1) We do not allow '@' char
2) We do not allow spaces/tabs/newline/carriage return
3) Of course, we do not allow names that already exist

Cheers

**Comment by darozak** [comment]
Awesome! It's working nicely now.
