### ISSUE TITLE
Rename allows me to choose an existing name

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#45]
I was able to rename my spacecraft to "carlos" which is already in use by another user.  I received an email confirming that the name change had occurred and confirmed this was the case in the database.  However, when I tried sending an email to carlos@advolition.com I was told that the drone belongs to another user and I don't have permission to access it.  We need to make sure that the user doesn't rename their drone to something that's already being used by another drone.  Since email names are case insensitive we also need to make sure someone doesn't name their drone "Carlos" when another drone is already called "carlos" (lowercase C).

**Comment by crodnun** [comment]
Fixed now. We do validations (they were not added yet)

**Comment by darozak** [comment]
This issue has been fixed.  Thanks so much!
