### ISSUE TITLE
Creating sql files to automatically populate tables with in-game data

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#48]
Carlos, Can you help me create additional .sql files in the game-engine/sql/ directory that will automatically populate the database with resource, protocol, and query-related data? The .sql files in this directory would be called every time the game system is restarted, ensuring that all the static tables are populated with the most current game data.  

If you can set up these files with token data (as you already have with objects_load.sql), I can start populating them with data for additional orbital objects, resources, protocols, and queries. Would this work?

Dave

**Comment by crodnun** [comment]
Hi Dave, for this purpose I have an script called **dump.sh**, I have uploaded it to develop branch here:

https://github.com/Darwin-River/Ex-Machinis/blob/develop/game-engine/scripts/dump.sh

I use it to generate periodic backups of the dynamic tables we have inside the system, this way in case of disaster we can populate the DB again with the same data we have right now.

Let me know if this is OK for you. If you look at the script, you can see that I generate a single SQL file for all the tables, including the objects one (the old objects SQL file would not be necessary now as we include it inside the dump script).

The purpose of this script is just to export the data we have so far and be able to import it easily if we need to re-create the DB. It only picks the dynamic data, users are not considered so far.

At the server (advolition) it is installed under **/home/forth/game-engine/bin/scripts** and available at PATH. Take into account that it loads a .env file that must be present at the same directory (this file has the DB credentials).

You can easily customize your own scripts (if needed) to only dump those tables you are interested in, but in my opinion a single .sql file to be loaded is the best approach to recover a DB,  easier than using multiple files.

Here:
https://github.com/Darwin-River/Ex-Machinis/blob/develop/game-engine/db-backup/exmachinis_tables.sql

you have the latest backup generated.

**Comment by darozak** [comment]
Hi Carlos.  I think your current approach works well!  If I understand it correctly, the dump.sh script routinely exports the current content of static tables (ie. the tables that do not change as a result of player activities) into a back-up file, which can be used to recover this data or port it to another installation (ie advolition -> exmachinis).  If I "program" the Ex Machinis world by adding resource, protocol, or query data to the current database using a DB client, this data will be preserved in examachinis_tables.sql for future use.  Is this correct?  How frequently does dump.sh back up the data?

**Comment by crodnun** [comment]
Hi Dave,  yes your assumption is correct. Right now I run it manually every time we add new changes,  just to keep a copy of them, but we can program it at cron if required (maybe a daily backup could be enough).

**Comment by darozak** [comment]
Yes.  I think it the backup should be run daily.  Can you set it to do so?   Overwise, this is a good solution!  It's definitely better than what I had been proposing.

**Comment by crodnun** [comment]
OK Dave, added at advolition server (for the moment, we only work there, when ready to move to production we can easily do the same there). 

I put it inside our daily "housekeeping.sh" routine that runs from the cron everyday at midnight.

We will keep 2 copies (current and previous day).

Repository updated with the same.

**Comment by darozak** [comment]
Perfect!  Thanks.
