### ISSUE TITLE
Drones return output from the print command in their emails

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#5]
Standard FORTH uses the print command (".") to create outputs for the user to read.  In Ex Machinis, these outputs need to be accumulated in a buffer and returned to the user via an email when the drone finishes running the user-invoked script.

**Comment by crodnun** [comment]
So far, we have implemented this feature. Maybe in the future we need to raise new issues to tweak it a bit but I think that this issue should be closed or additional requirements included here.

**Comment by darozak** [comment]
Agreed.  This feature is working now. We'll close this requirement.  Thanks!
