### ISSUE TITLE
Minor typo at documentation (query command)

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#54]
Here:
![image](https://user-images.githubusercontent.com/16229970/70152240-25598b00-16ad-11ea-86ee-a30a47586962.png)

we have a typo when enumerating the parameters we can receive (this line should be within the list).

**Comment by darozak** [comment]
Fixed it [here](https://github.com/Darwin-River/Ex-Machinis/wiki/Database-Searches/f65b665dc6bd07cfc0095e9788e4b4082b77d136).  Thanks!
