### ISSUE TITLE
Reuse perform command for future extensions of the VM

### ISSUE THREAD

**Issue by crodnun** [Darwin-River/Ex-Machinis#55]
Hi Carlos. I suggest we use the existing "perform" routine as the hook for all spacecraft commands.

When someone executes "perform", the Game Engine will pull the first number off the stack and determine whether it indicates that the Game Engine should perform a special command. This would be a command that is not addressed in either the protocols or queries tables but that we might add in the future.

If the number does not belong to a special command, the Game Engine will search protocols.id for an entry that matches the number it pulled from the stack.

If it fails to find the value in protocols.id, it will search for the number in queries.id.

If it can't find the number there, it will conclude that the command doesn't exist.

In other words, every time the "perform" command is called the Game Engine engine will follow a simple branching structure:

If the number on the stack corresponds to a specially-defined command, execute that command and then end the routine. (We haven't defined any of these commands yet.)
Else, if the number on the stack matches a protocol ID, implement that protocol and end the routine.
Else, if the number on the stack matches a query ID, implement that query and end the routine.
4, Else, the command is undefined. End the routine without doing anything.
In practice, we'll assign IDs in one number range (say 1001 - 2000) to protocols and IDs in another number range (say 2001 -3000) to queries. Special commands may occupy the value range from 1-1000.

Dave

**Comment by darozak** [comment]
I captured this idea in the design manual (https://github.com/Darwin-River/Ex-Machinis/commit/f2a9f0cfdb84f52dc3f342a7a056d8b91e824577) so that it will be spelled out there if we ever need to code a protocol that can't be described by the database.
