### ISSUE TITLE
The registrar should provide a more informative response to already registered users

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#6]
When an existing user sends a registration request to the registrar he receives a brief email saying that he has already registered.  This email should be modified to include a list of the player's existing drones in case he has forgotten what they are.

**Comment by crodnun** [comment]
PHP codes have been modified to answer with the list of drones when already registered

**Comment by darozak** [comment]
This is almost working.  But something's not quite right.  

When I sent a registration request from my Darwin River email address I got the following response:

Registration error: your email is already registered with the following drones: SN270327@exmachinis.com, SN671629@exmachinis.com, SN592237@exmachinis.com, 

However, I've always been accessing SN834430@exmachinis.com from this email address and its not on the list I received with the registration error.

**Comment by crodnun** [comment]
OK, sorry. Seems I messed it up using the wrong ID (we have inside the DB many, lol... company_id, agent_id, user_id,...) and I was using the user one but each agent is associated with a company_id (at least at current model). Should be fixed now

**Comment by darozak** [comment]
It's working now.  Thanks!
