### ISSUE TITLE
Create a web page to display a table of astronomical objects

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#61]
Players and visitors will use the Ex Machinis website to search and browse in-game data on planets, moons, asteroids, spacecraft, resources, and companies.  The first of these pages will retrieve and display data on orbital objects in a searchable and sortable table.  Planets, moons, asteroids, and comets are all examples of the types of orbital objects that are listed in this table.

The table should contain sortable columns for ObjectID, ObjectName, ObjectType, and CentralBody and the user should be able to filter the contents based on keyword,

The table should be build using the following SQL query or something similar:

```
SELECT objects.object_id AS ObjectID, objects.object_name AS ObjectName, objects.object_type AS ObjectType, objects_1.object_name AS CentralBody, objects_1.object_id AS CentralBodyID
FROM ((objects LEFT JOIN abundancies ON objects.object_id = abundancies.location) LEFT JOIN objects AS objects_1 ON objects.central_body_object_id = objects_1.object_id) LEFT JOIN resources ON abundancies.resource = resources.id
WHERE (((objects.object_name) Like "*" & [Search term?] & "*")) OR (((objects.object_type) Like "*" & [Search term?] & "*")) OR (((objects_1.object_name) Like "*" & [Search term?] & "*"));
```
Eventually, the user will be able to click on the name of an orbital object or central body to go to another page with more information on the objects. But this requirement will be addressed as part of another issue.

**Comment by darozak** [comment]
Fernando wrote:

Hello David. I think the search page is more or less done. Can you take a look? Do you want anything different?

The one thing I regret is the lack of transition/animation... it changes abruptly. I didn't find an easy way to approach it.

Are you handling database structures changes in some way, or you just do it? I think it would be good to add indexes for name, type and main object... not to mention a foreign key.

And another thing: on the template there is a lens icon on the header menu... that can be used for a quick search that redirects to this page...

**Comment by darozak** [comment]
Hi Fernando, the table for Astronomical Objects looks amazing!  The search and sort features work well.  I can see how an animation would be nice but it's not necessary.

- Please push your changes to the develop branch so we don't loose track of them.

I notice that you've already hyperlinked the object names and IDs to take you to more detailed pages on each.  This is perfect.  I'll prepare a mock-up of what these pages should contain to guide your design.  Each page will provide detailed orbital data for the object as well as lists of what objects and spacecraft are orbiting them and what resources are available at the location.

- In the meantime, can you hyperlink the object names that are listed in the Central Body column as well?

It should be fine if you want to add indexes to the different fields.  I don't think they will adversely affect any other routines.

If we do use the lens icon, it shouldn't be linked to only astronomical objects.  There will be many different data sets to search.

**Comment by freelancefrivas** [comment]
Ok, I did what you requested.
About the lens icon... maybe it's not a good idea to have a general search then. Or at least there's no easy approach.

**Comment by darozak** [comment]
Thanks for the drop down menus.  This will really help to organize the content.  

Would it be possible to build a similar structure into the menus along the left side of the page, perhaps using one icon for data and another for documentation?  I like how this is done in the template demo.

I like the idea of a general search but we should probably hold off on implementing it if there isn't an easy solution.

**Comment by freelancefrivas** [comment]
Ah, I was leaving the sidebar for a user menu...

**Comment by darozak** [comment]
The side menu will work really well for general site navigation (documents, data tables, etc..) since it stays on the screen as you scroll down the page and is always available.

**Comment by darozak** [comment]
The astronomical objects table is good to go! I'll create a separate issue that details the design of the details page for a specific object.
