### ISSUE TITLE
Create web pages to display spacecraft data

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#62]
We will need two types of dynamic web pages to display spacecraft data.  

The first page will be a searchable and sortable list of all spacecraft with hyperlinks to more detailed information on the referenced spacecraft, owner, and location (astronomical object).  The SQL query for the table would look something like this:

```
SELECT agents.agent_id AS ID, agents.name AS Drone, hulls.name AS Hull, users.name AS Owner, objects.object_name AS Location
FROM ((agents LEFT JOIN users ON agents.user_id = users.user_id) LEFT JOIN objects ON agents.object_id = objects.object_id) LEFT JOIN hulls ON agents.hull_type = hulls.id;
```

The second type of web page would have details on the specific spacecraft to include lists of their on-board resources and events that have recently affected them.  This will be detailed in a separate issue.  For now we will just focus on listing the in-game spacecraft.

**Comment by freelancefrivas** [comment]
I don't think it makes sense to search by hull type, right?

**Comment by freelancefrivas** [comment]
And do you prefer anything in particular to be displayed in the results table (as data columns)?

**Comment by darozak** [comment]
I agree that the users probably won't want to search by hull type.

I the displayed columns should include the spacecraft's ID, name, hull type, owner (username), and location (astronomical body).

The name will hyperlink to a detail page for the spaceship, the username will link to a detail page for the user (i.e. company), and location will link to a detail page for the astronomical object that the spacecraft is orbiting (Earth, Moon, Mars, etc...).

**Comment by darozak** [comment]
Thanks Fernando.  The spacecraft table is perfect!
