### ISSUE TITLE
Create a web page to display protocols

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#63]
Spacecraft perform in-game actions by invoking specific protocols.  These protocols are defined in the protocols table of the SQL database.  

We need to have a web page that displays these protocols in table format.

- The table will display the protocol ID, name, and description.
- The data will always be sorted in ascending order by protocol ID.
- It will be possible to search the name and description fields using a single keyword.
- None of the fields will be hyperlinked.
- The page will be accessible from the Documents drop-down menu: Documents>Protocols.

Here's a suggested query script to make the table:
```
SELECT protocols.id, protocols.name, protocols.description
FROM protocols
GROUP BY protocols.id, protocols.name, protocols.description;
```
Here's an example of how the table could be organized:
![Protocols](https://user-images.githubusercontent.com/33500329/72207036-af420400-3462-11ea-9858-da4c87d47c0c.PNG)

**Comment by freelancefrivas** [comment]
Are you sure IDs are needed and that you want a table? Take a look at the "Tabs & accordions" section https://www.templatemonster.com/demo/71708.html .

**Comment by freelancefrivas** [comment]
I guess it's ok to use a table in the end... the descriptions are short.

**Comment by freelancefrivas** [comment]
Another question: these commands are all related to agents/drones?

**Comment by darozak** [comment]
The protocol IDs will be used by the players to invoke the action via the FORTH perform command. So it is important that they be listed.

There will be quite a few protocols so I think a table layout will work best.

Yes. The protocols all relate to actions that can be performed by agents/drone.

**Comment by freelancefrivas** [comment]
Ok, you can take a look now. I used another style: https://advolition.com/protocols .

**Comment by darozak** [comment]
Hi Fernando.  This looks great!  I really like the simple table and how the table automatically filters the content as you type a keyword.   Can you use the same strategy with the [query table](https://github.com/Darwin-River/Ex-Machinis/issues/64)?
