### ISSUE TITLE
Create a web page for displaying query commands

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#64]
Spacecraft will be able to access in-game data via the use of a FORTH-based query command.  The command works by invoking a specific query script via it's query ID.

We need to create a web page that displays a searchable list of queries that are available to the user:
- The table will display the query ID, name, and description.
- The data will always be sorted by query ID in ascending order.
- Users will be able to search the name and description fields by a common keyword.
- There will not be any hyperlinked fields in this query.
- The query table will be accessible via the Documents pull-down menu: Documents>Queries

Here is a suggestion for the table's query script:
```
SELECT queries.id, queries.name, queries.description
FROM queries
ORDER BY queries.id;
```
And this is what the table should look like:
![Queries](https://user-images.githubusercontent.com/33500329/72207359-65f3b380-3466-11ea-9a60-685dac6b39e6.PNG)

**Comment by freelancefrivas** [comment]
Hi. So do you think there will be a big amount of these queries? For example more than 50?

**Comment by darozak** [comment]
There probably won't be more than 50.

**Comment by freelancefrivas** [comment]
Ok, I've uploaded it: https://advolition.com/query-commands . As this one has longer descriptions, the table is not that elegant. You can consider accordions, some style modification, or just leave it like that...

**Comment by darozak** [comment]
Hi Fernando. This looks great! Let's keep it as is.
