### ISSUE TITLE
Create a web page to display resource data

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#65]
We need to create a web page to display the different resources that are available to players and spacecraft.  The Resources page will display a table with the following properties:
- The table will display resource ID, name, description, and unit mass in kg.
- The table will always be sorted by resource ID in ascending order.
- The name and resource fields will be searchable via a common keyword search.
- The name field will be hyperlinked to a page containing more information on the specific resource (to be detailed in a later issue).
- The Resources page will be accessible via the Data drop-down menu: Data>Resources.

Here is a query script that can be used to generate this table:
```
SELECT resources.id, resources.name, resources.description, resources.mass
FROM resources
ORDER BY resources.id;
```
And this is an example of how the table should be laid out:
![Resources](https://user-images.githubusercontent.com/33500329/72207580-8b81bc80-3468-11ea-927a-011629633ede.PNG)

**Comment by freelancefrivas** [comment]
Ok, it's up now, so you can take a look: https://advolition.com/resource .

**Comment by darozak** [comment]
Thanks Fernando!  This looks great!  We have one more list-type page to develop that will display in-game events.  I'm working on the query and table layout now and will post the requirement today or tomorrow.  After that, we can start designing the detail pages for companies, spacecraft, resources, and objects.
