### ISSUE TITLE
Create a web page to display company data

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#66]
Each player represents a separate in-game company.  In fact the user name is synonymous with the company name.

We will need a web page to list all of the active companies (users) along with some basic stats on the company.  Table entries will also be hyperlinked to more detailed pages on the individual companies (the subject of a later issue).
- The table will display the user ID, name, age (days since creation), spacecraft (count), and credits.
- The data will be sortable by ID, name, age, spacecraft, and credits.
- The data will be searchable by ID and name.
- The name field will be hyperlinked to a user-specific page with more details about the user's company (the subject of another issue).
- The Companies page will be accessible from the Data drop-down menu: Data>Companies.

Here is an example of the table query script, which counts the number of drones owned by the company and computes age in days by subtracting the user creation date from the current date.
```
SELECT users.user_id AS ID, First(users.name) AS Name, DateDiff("d",First(users.created_at),Now()) AS Age, Count(agents.agent_id) AS Spacecraft, First(users.credits) AS Credits
FROM users LEFT JOIN agents ON users.user_id = agents.user_id
GROUP BY users.user_id;
```
Here's a screenshot showing what the table should look like:
![Companies](https://user-images.githubusercontent.com/33500329/72208083-ce459380-346c-11ea-9bb9-3ef85b68af02.PNG)

**Comment by freelancefrivas** [comment]
Companies are not in a database table anymore? Or is there something I'm missing...

**Comment by darozak** [comment]
Yes.  Companies are now the same as users.  Company_ID = User_ID; Company_Name = User_Name; etc...

**Comment by darozak** [comment]
This is perfect!  Thanks Fernando.
