### ISSUE TITLE
Create a web page to display in-game events

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#68]
Ex Machinis maintains a detailed log of all the events that occur in the game.  This log is an important resource for players who are interested in seeing what has transpired and troubleshooting the code they are writing for their spacecraft.  The website needs a table that displays all observable events (observations.drone = 0).  Here are the key features of this table:
- The data will always be sorted in descending order of the time of the event.
- Players will be able to filter the contents of the table using a single keyword search.
- All listed companies, drones, resources, and astronomical objects will be hyperlinked to detail pages.
- The "Locked" field contains a Boolean value which should be rendered opened (false) or closed (true) lock in that column.  If the field is null, then it will not contain a lock.

Here is an image of what the events table should look like:
![Events Table](https://user-images.githubusercontent.com/33500329/72682744-80e5a980-3a9e-11ea-96b9-2b0dbd4b69c9.PNG)

And here is an example of the events query.  Unfortunately, this query is fairly complex because it pulls together data from many different tables.
```
SELECT observations.drone AS Observer, observations.Time AS ObservationTime, events.timestamp AS [Time], agents_1.user_id AS ActingCompanyID, users_1.name AS ActingCompanyName, agents.agent_id AS ActingDroneID, agents.name AS ActingDroneName, protocols.name AS [Action], event_types.name AS Effect, agents_1.user_id AS AffectedCompanyID, users_1.name AS AffectedCompanyName, agents_1.agent_id AS AffectedDroneID, agents_1.name AS AffectedDroneName, events.resource AS AffectedResourceID, resources.name AS AffectedResourceName, events.locked, events.new_quantity AS NewQuantity, events.new_credits, events.new_location AS NewLocationID, objects.object_name AS NewLocationName
FROM observations LEFT JOIN (((((((((events LEFT JOIN event_types ON events.event_type = event_types.id) LEFT JOIN objects ON events.new_location = objects.object_id) LEFT JOIN resources ON events.resource = resources.id) LEFT JOIN actions ON events.action = actions.id) LEFT JOIN protocols ON actions.protocol = protocols.id) LEFT JOIN agents AS agents_1 ON actions.drone = agents_1.agent_id) LEFT JOIN agents ON events.drone = agents.agent_id) LEFT JOIN users ON agents.user_id = users.user_id) LEFT JOIN users AS users_1 ON agents_1.user_id = users_1.user_id) ON observations.event = events.id
WHERE (((observations.drone)=0) AND ((observations.Time)<=Now()))
ORDER BY events.timestamp DESC;
```

**Comment by freelancefrivas** [comment]
Don't you want it to be searchable by other fields as well?

**Comment by darozak** [comment]
Yes.  It should be searchable via any text fields.  But there will only be one search box that filters the list as you type.

**Comment by freelancefrivas** [comment]
Is this correct?
`agents_1.user_id AS ActingCompanyID, users_1.name AS ActingCompanyName,`
`agents_1.user_id AS AffectedCompanyID, users_1.name AS AffectedCompanyName`
Affected and acting is always the same?

**Comment by darozak** [comment]
No.  That's a mistake.  I'm glad you caught that.   Affected fields should be linked to agent or user tables.  Acting fields should be linked to agent_1 or user_1 tables.  Here's the corrected query statement:
```
SELECT observations.drone AS Observer, observations.Time AS ObservationTime, events.timestamp AS [Time], agents_1.user_id AS ActingCompanyID, users_1.name AS ActingCompanyName, agents_1.agent_id AS ActingDroneID, agents_1.name AS ActingDroneName, protocols.name AS [Action], event_types.name AS Effect, agents.user_id AS AffectedCompanyID, users.name AS AffectedCompanyName, agents.agent_id AS AffectedDroneID, agents.name AS AffectedDroneName, events.resource AS AffectedResourceID, resources.name AS AffectedResourceName, events.locked, events.new_quantity AS NewQuantity, events.new_credits, events.new_location AS NewLocationID, objects.object_name AS NewLocationName
FROM observations LEFT JOIN (((((((((events LEFT JOIN event_types ON events.event_type = event_types.id) LEFT JOIN objects ON events.new_location = objects.object_id) LEFT JOIN resources ON events.resource = resources.id) LEFT JOIN actions ON events.action = actions.id) LEFT JOIN protocols ON actions.protocol = protocols.id) LEFT JOIN agents AS agents_1 ON actions.drone = agents_1.agent_id) LEFT JOIN agents ON events.drone = agents.agent_id) LEFT JOIN users ON agents.user_id = users.user_id) LEFT JOIN users AS users_1 ON agents_1.user_id = users_1.user_id) ON observations.event = events.id
WHERE (((observations.drone)=0) AND ((observations.Time)<=Now()))
ORDER BY events.timestamp DESC;
```

**Comment by freelancefrivas** [comment]
Ok. And you don't want this table to be sortable by any other fields? It's not that much extra work...

**Comment by freelancefrivas** [comment]
Also, what does "locked" represent?

**Comment by darozak** [comment]
Ok.  Let's make each of the fields, other than the Lock, New quantity, and New Credits fields sortable.  I'm not sure how useful it will be but I can see how you might want to sort by different fields to organize the events.

The Lock field indicates that the particular resource is in use (true).

**Comment by freelancefrivas** [comment]
Ok, you can take a look now https://advolition.com/in-game-event . I struggled a little in dealing with different screen sizes. In the end I removed the sorting of the other columns because of this... but I don't think it's important.

**Comment by darozak** [comment]
Thanks Fernando! This seems like a very reasonable solution for dealing with so much data.  Just a few minor chages:
- Can you change the url to https://advolition.com/events so that it's easier to type and remember?  Now that I say this, the same should also be done for some of the other display pages: objects, companies, resources, and queries.  Always a single word and always plural (since the tables list multiple items).  Sorry I didn't pick up on this earlier.
- Also, can you move the lock icon from the right side of the table to a position just to the left of the "Affected Resource" column, since it applies specifically to the resource and nothing else? In fact, the icon should be right justified so that it is physically nearer to the affected resource name than the affected spacecraft.

**Comment by freelancefrivas** [comment]
Ok, did those changes. 
I also noticed Carlos mentioned the dates were wrong. I think that should be fixed now.

**Comment by darozak** [comment]
Thanks Fernado!
