### ISSUE TITLE
Create an astronomical objects detail page

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#69]
We'll need to create a page that displays the details for a particular astronomical object.  The page will be accessible by clicking on an object's name wherever it appears elsewhere in the website.

The details page will provide orbital information as well as a list of available resources and local spacecraft.  Here's an example of how the page could be laid out:
![Object Details](https://user-images.githubusercontent.com/33500329/72805436-dd70d200-3c20-11ea-93aa-c2a298275718.PNG)

The extractable resource and local spacecraft tables will generally be short and won't need to be sortable or searchable.

I used three queries to obtain the data for this page:
```
SELECT objects.object_id, objects.object_name, objects.object_type, objects.central_body_object_id, objects_1.object_name AS CentralBodyName, objects.epoch, objects.semimajor_axis, objects.eccentricity, objects.periapsis_argument, objects.mean_anomaly, objects.inclination, objects.ascending_node_longitude, objects.mean_angular_motion
FROM objects LEFT JOIN objects AS objects_1 ON objects.central_body_object_id = objects_1.object_id;

SELECT abundancies.location, abundancies.resource, resources.name, abundancies.multiplier
FROM abundancies LEFT JOIN resources ON abundancies.resource = resources.id;

SELECT agents.agent_id AS ID, agents.name AS Drone, hulls.name AS Hull, users.name AS Owner, agents.object_id AS LocationID, objects.object_name AS Location
FROM ((agents LEFT JOIN users ON agents.user_id = users.user_id) LEFT JOIN objects ON agents.object_id = objects.object_id) LEFT JOIN hulls ON agents.hull_type = hulls.id;
```
As with previously designed pages, all object, company, spacecraft, and resource names will be hyperlinked to pages that display additional details on each.

**Comment by freelancefrivas** [comment]
Ok, I did a page for the space object view... which is subject to changes. Some notes:
- I didn't know whether to choose this header (for the title) or the one with the space background.
- As you'll see, I used some components from the template to make it more visual. If you want me to turn something into a regular table instead, it won't be much work.
- Considering that the three columns of data at the top are piled up on mobile (to become one), how would you group the fields? I couldn't decide.
- I assumed the field 'multiplier' represented the resource's amount...

**Comment by darozak** [comment]
Fernando, This looks great!  I like the new formats you've used for the data.  The multiplier reflects the prevalence of the resource.  The higher the number, the more efficient your resource extraction operation will be.  Here are some additional thoughts:

- Can we try using the space background for this?
- Can you link the extractable resource names to a details page on that resource?
- Perhaps you could use two columns instead of three, arranging them like in the example above.

**Comment by darozak** [comment]
Hi Fernando.  Could you add a third table to this page, which shows the astronomical objects that are orbiting the current object?  The table would also report the number of spacecraft that are located at each of these objects.

Here's an example of how the table would look:
![200201 Object Details](https://user-images.githubusercontent.com/33500329/73595645-062e7c80-44e9-11ea-804c-248893752223.PNG)

And this is the script I used for the orbiting bodies query:
```
SELECT First(objects.central_body_object_id) AS CentralBodyID, objects.object_id AS OrbitingObjectID, First(objects.object_name) AS OrbitingObjectName, First(objects.object_type) AS OrbitingObjectType, Count(agents.agent_id) AS SpacecraftCount
FROM objects LEFT JOIN agents ON objects.object_id = agents.object_id
GROUP BY objects.object_id;
```

**Comment by freelancefrivas** [comment]
Ok, I'm glad you liked it. I did those modifications now.

**Comment by darozak** [comment]
This is awesome! That was fast and everything works perfectly!  I'll close out this issue and post a couple more to deal with companies and drones.  I probably won't get to this until tomorrow though.  I'll need to prototype them in Access first.
