### ISSUE TITLE
Getting multiple emails from simple scripts

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#7]
When i send this program to my drone:

<script>
10 10 = IF 1 . ELSE 0 . THEN
</script>

I get three emails.  One email says "1", another says "0", and the third email is blank.

Also sending a the following instruction

<script>
10 10 + .
</script>

returns two emails.  One email is blank and the other contains "20"

I should really only be getting one response for each of these scripts.

**Comment by crodnun** [comment]
I already noticed this today during my tests, should be fixed now, empty messages or those containing non printable chars will not be sent to the user by email.

Please test it again and let me know the results.

**Comment by darozak** [comment]
Fixed!  Thanks so much!
