### ISSUE TITLE
Add code block formatting to CSS files

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#71]
Fernando, 

I [added ](https://github.com/Darwin-River/Ex-Machinis/commit/d00fd033c43b591d81ff08b8971527535d33902f) the following CSS script to https://advolition.com/players-manual to format the code blocks.  However, I couldn't locate the correct CSS template files to add it to to make the style generally applicable to \<pre\> \<code\> combinations throughout the website. 

Here's an example of the style code that I added to the Player's Manual:
```
<pre style="color:white; border: 1px solid white; display:block; margin-top:20px; padding:20px 40px;">
<code>&lt;run&gt;
  2 3 + .
&lt;/run&gt;</code></pre>
```

Here's the generalized code that I would like to add to the appropriate CSS template:

```
pre code {
  color:white; 
  border: 1px solid white; 
  display:block; 
  margin-top:20px; 
  padding:20px 40px;"
}
```
Which CSS file should I add this to?

Also, which file CSS file(s) would I access to modify the way paragraphs are generally displayed and formatted?

**Comment by freelancefrivas** [comment]
Hello David.
I just moved that code to /resources/assets/sass/custom-styles/advolition.scss . That is the file I'm using for custom CSS code added for this project, that goes beyond the template. Maybe I should name it exmachinis.scss ?
But if you modify the file alone, you won't see the changes. You have to run `npm run prod` (in the project's root folder), which rebuilds the app.js and app.css in the 'html' folder, which is where the change should take place. If you want to work continuosly touching css (or javascript), you can run `npm run watch`, so any change you make to the files instantaneously rebuilds those files.

**Comment by freelancefrivas** [comment]
Ah, if you make general rules for paragraphs, mind that it can affect other contents...

**Comment by freelancefrivas** [comment]
Ah, forgot to say something kind of basic. In order to run npm, you have to install node.js and npm first...

**Comment by darozak** [comment]
Thanks Fernando.  Would you be able to install these on the server for us?

**Comment by darozak** [comment]
I agree that advolition.scss should be renamed exmachinis.scss.

**Comment by freelancefrivas** [comment]
npm is for the front end, is a Javascript package manager.
I renamed the file, will commit it later.
Ok, I'll install those. What would be good too is to create a script that executes every time a new GIT push is made, and automatically re-builds the app.js and app.css...

**Comment by freelancefrivas** [comment]
Ok, just installed those and checked that it works. By the way `npm run dev` is more adequate for this test server than `npm run prod`.

**Comment by darozak** [comment]
Thanks!  Just to make sure I understand the process:

1. Edit the css code in /resources/assets/sass/custom-styles/exmachinis.scss (assuming you changed the name).
2. Enter `npm run prod` in the root directory.
3. Refresh the web page to observe changes.

Correct?

**Comment by freelancefrivas** [comment]
Yes, that's correct. Although I think `npm run dev` is more adequate for this test server.

**Comment by darozak** [comment]
Ok. Got it.  My mistake.  You had suggested `npm run dev` above.  Thanks for your help with this.
