### ISSUE TITLE
The Event Engine has stopped updating the observation table.

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#74]
It appears that the Event Engine stopped updating the observation table some time after 23 January.  As you can see from the following screen shots, we have 75 events but the last recorded observation was for event 68.  Furthermore, the Event Engine stopped setting the events.outcome field to 1 or a negative value (if there is an error) after event 69.  Did something cause the Event Engine to crash?

Observations Table:
![200129 Observation Tabe Capture](https://user-images.githubusercontent.com/33500329/73359029-e8091800-426d-11ea-8f36-f483114741e0.PNG)

Events Table:
![200129 Event Table Capture](https://user-images.githubusercontent.com/33500329/73359036-edfef900-426d-11ea-9651-d8f30fcfe76b.PNG)

**Comment by crodnun** [comment]
I have detected a couple of issues:

1) First related with mysql installation, seems that something has been updated there and the binaries are no longer working. We are not able to work with them anymore.

2) I have detected the bug related with the events management, but I am not able to patch it till clarified point 1. We do not have mysql to link and generate new binaries for the game/events engine.

**Comment by crodnun** [comment]
This issues should be fixed now, after amending the 2 points detail above:

- We had a couple of bugs when dealing with the NULL feature for UI and also some problems with mysql installation and latest machine updates that removed mysql stuff for the engines.

All them should be solved now, and observations table is now receiving data.

**Comment by darozak** [comment]
Thanks Carlos. You're amazing at tracking these things down!
