### ISSUE TITLE
DB Time and Server time appear to be different

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#75]
The website's events table is designed to display only those events who's obervations.time is <= the current time.  This is meant to ensure that the website doesn't report events that have not yet been observed on Earth.

When events happen in Earth orbit (i.e. nearby) they should be observed immediately.  However I noticed that this is not occurring and think I know why:  The DB appears to be recording time in GMT while Now() function, which is used in the query ("observations.time <= now()"), appears to be pulling the local time (ET).   

Is there any way to either set the SQL time to ET or or the Now() function to GMT?

Not sure if this is a question for Carlos or for Fernando, so I'm sending it to both.

Thanks for giving this some thought!

**Comment by crodnun** [comment]
Hi Dave, not sure what you are looking for ...  the dates stored at DB use the server date (local time: ET) and normally the browsers display the dates using local time for each user. Not sure what is the logic or queries now running from the UI. Could you complete this information to guess what we need there?

As an example, if I generate an event and compare with server date:

```
| 134 |          3 |    157 |      1 |       1 |     2 |        0 |         0 |      0 |         NULL |        NULL |            1 |             NULL |        40 | 2020-01-30 14:13:02 |
+-----+------------+--------+--------+---------+-------+----------+-----------+--------+--------------+-------------+--------------+------------------+-----------+---------------------+
34 rows in set (0.00 sec)

mysql> quit
Bye
[forth@advolition] # date
Thu Jan 30 14:13:19 UTC 2020
```

Checking the server timezone:

```
[forth@advolition] # cat /etc/timezone 
Etc/UTC
```

What you would like to use?
Thanks

**Comment by freelancefrivas** [comment]
You can check again now. I was using a time function that was returning the date and not the time, so it was probably updating day by day...

**Comment by darozak** [comment]
It looks like Fernando found the problem.  Everything is working correctly now.  Thanks!

Carlos, Thank you also for looking into this.  UTC is fine and probably makes the most sense.

Thank you!!
