### ISSUE TITLE
We probably need an About Us page

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#76]
I'd like to add an About Us page to the website, which will be accessible form the menu bar in the header. For now the page will include the following place-holder text. I'll add to this at a later point.

> Ex Machinis is an online multiplayer space simulation designed to expose players to programming and robotics. In the game, which takes place against the backdrop of our real-time solar system, players program remotely piloted spacecraft to mine, manufacture, and trade goods and services.
> 
> The game uses augmented reality to project a parallel universe upon our own. In the game's re-imagined post-war history, world leaders embraced space exploration and colonization as a means of protecting mankind form the global threats that emerged in the wake of the second world war.

**Comment by freelancefrivas** [comment]
Ok, added: https://advolition.com/about-us . To edit the file you can go to /resources/views/pages/about-us.blade.php .

**Comment by darozak** [comment]
Excellent!  Thanks for turning this around so quickly.
