### ISSUE TITLE
Create a Company Details page

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#77]
We'll need a page to display detailed information on a specific company.  In addition to reporting basic company stats, the page will list and link to all spacecraft that are owned by the company as well as their current locations.

Here's an example of what the page should look like:
![200202 Company Details](https://user-images.githubusercontent.com/33500329/73612550-bcae6200-45ba-11ea-8a37-ec5142bff995.PNG)

This is the simple query that I used to retrieve company stats from the DB:
```
SELECT users.user_id AS ID, users.name AS Name, users.created_at AS Founded, users.credits AS Credits
FROM users;
```

And here is the query that I used to create the list of company spacecraft:
```
SELECT agents.user_id AS OwnerID, agents.agent_id AS DroneID, First(agents.name) AS DroneName, First(hulls.name) AS HullType, First(objects.object_name) AS Location, First(hulls.cargo_capacity) AS MaxCargo, First(IIf([new_cargo] Is Null,0,[new_cargo])) AS CurrentCargo, First(agents.object_id) AS LocationID
FROM ((agents LEFT JOIN events ON agents.agent_id = events.drone) LEFT JOIN hulls ON agents.hull_type = hulls.id) LEFT JOIN objects ON agents.object_id = objects.object_id
GROUP BY agents.user_id, agents.agent_id;
```

**Comment by freelancefrivas** [comment]
Question: when the last event of an agent has a positive number in the new_cargo field, it means it has cargo on board, but in any other case it doesn't? No event can occur between loading and unloading cargo?

**Comment by darozak** [comment]
Yes.  That's correct that correct that a positive number means there is cargo on-board.  All other cases mean the cargo bay is empty.  However, there shouldn't be negative values in this field.  If there are, then there is an error at the game or event engine that we need to address.  

Other events can occur between loading an unloading cargo.  But the event engine is intended to recognize and address from any conflicts that might arise as a result.

**Comment by freelancefrivas** [comment]
Ok, I finished this page, you can take a look: https://advolition.com/companies/5 .

**Comment by darozak** [comment]
Hi Fernando.  I love how you laid out the spacecraft table.  The icons also work very nicely!  I do see several issues that need to be fixed:
1. Can you use a different format for the data at the top of the page?  The font you use for Id, Founded On, and Credits is hard to read.
2. If you click on any of the locations it mistakenly takes you to another companies details page rather than an orbital objects details page.
3. I don't think you're displaying cargo capacity correctly.  For example, North Star's Traveler spacecraft should have 25 kg in its hold (as shown in the page layout example at the top of this issue).  However, on the web page (https://advolition.com/companies/2), it indicates 0 kg of cargo.

**Comment by freelancefrivas** [comment]
Ok, fixed those.

**Comment by darozak** [comment]
Nice!  Works great now. Thanks for prepping this page!
