### ISSUE TITLE
Create a Join the Game page

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#79]
We should create a "Join the Game" page which is accessed from the top menu bar and gives players access the the same form that is currently being displayed at the bottom of every page.  Moving this form from the page footer to its own page, will allow for a more descriptive form and make it easier for us to invite users to register.  The option will also be more visible at the top of the page.

**Comment by freelancefrivas** [comment]
You don't want to add any more fields, right? Just the name and email?
So you want to remove that from the footer? The only thing left in the footer will be the "About Us" column?

**Comment by darozak** [comment]
Correct.  No new fields in the Join the Game page.  Don't worry about removing it from the footer.  I'll take care of that.  I need to figure out what to replace it with.

**Comment by darozak** [comment]
I see you've added the page but it doesn't appear to be functional just yet.

**Comment by freelancefrivas** [comment]
Yes... I decided to add validation now that it has its own page (I mean checking if the email and company don't already exist) and I got stuck with a weird problem. I'll look into it now.

**Comment by freelancefrivas** [comment]
Ok, you can check it and test it now: https://advolition.com/register .

**Comment by darozak** [comment]
This works great!!  I'm glad that you added the email and company name checks.  Thanks for doing this.

**Comment by freelancefrivas** [comment]
No problem.
