### ISSUE TITLE
Fix the owner link on the spacecraft page

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#80]
If you go to https://advolition.com/spacecraft and click on a link in the Owner column, it takes you to a non-existent page.

**Comment by freelancefrivas** [comment]
I think maybe you meant the "name" column? Because that link was wrong. But the "owner" column... is it supposed to link to a user page? Or just no link?

**Comment by freelancefrivas** [comment]
Sorry, the name was right, I got it mixed with the company name just before. About the second point, I think your intention was that it links to the company page, so I set it to that.

**Comment by darozak** [comment]
Yes.  The name in the owner column should link to the corresponding company data sheet, which it does now. You've fixed the bug. Thanks!
