### ISSUE TITLE
Create a web page for listing buy orders

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#81]
Now that spacecraft can place buy orders, we need a web page for displaying these orders.  Here are the key features of the Buy Orders page:

- Visitors can use a single keyword to filter the table contents by Resource, Posted By and Location fields.
- The table will be sortable by the Resource, Posted On, Posted By, and Location columns.
- The Resource, Posted By, and Location fields will be hyperlinked to resource, spacecraft, and space object details pages.
- The URL for the Buy Order page should be https://advolition.com/buys
- The Buy Orders page will be accessible from the Data drop down menus at the top and side of the web page.

Here's an example of what the table should look like:
![200214 Buy Orders](https://user-images.githubusercontent.com/33500329/74575448-fab16b80-4f54-11ea-8246-6b3d4cfcdede.PNG)

The table uses the following query which in turn references a subquery.

Here is the main query that I used to create the above table:
```
SELECT agents.name AS PostedBy, resources.name AS Resource, Last(events.timestamp) AS PostedOn, Last(event_types.name) AS [Transaction], Last(events.new_credits) AS UnitPrice, Last(objects.object_name) AS Location, Last(events.new_quantity) AS MaxQuant, Last(sqInventory.Units) AS Available, [events].[new_quantity]-[sqInventory].[Units] AS Volume, events.drone AS DroneID, events.resource AS ResourceID, agents.object_id AS LocationID
FROM ((((events LEFT JOIN resources ON events.resource = resources.id) LEFT JOIN agents ON events.drone = agents.agent_id) LEFT JOIN objects ON agents.object_id = objects.object_id) LEFT JOIN event_types ON events.event_type = event_types.id) LEFT JOIN sqInventory ON (events.drone = sqInventory.drone) AND (events.resource = sqInventory.resource)
WHERE (((events.event_type)=5))
GROUP BY agents.name, resources.name, [events].[new_quantity]-[sqInventory].[Units], events.drone, events.resource, agents.object_id;
```

Here is the sqInventory query that is referenced by the main query:
```
SELECT events.drone, events.resource, Last(events.new_quantity) AS Units
FROM events
WHERE (((events.locked)=False) AND ((events.event_type)=1 Or (events.event_type)=2))
GROUP BY events.drone, events.resource;
```
In case it helps, I found a useful [tutorial](https://www.akadia.com/services/sqlsrv_subqueries.html), which demonstrates the use of SQL subqueries.

**Comment by freelancefrivas** [comment]
I created a view in the database for that subquery...

**Comment by darozak** [comment]
I can see the Buy Orders page but when I go there there is only the page title but no table.

**Comment by freelancefrivas** [comment]
Yes, I meant a MySQL view, to store that SQL code in the database.

**Comment by darozak** [comment]
Excellent!  Now I understand.

**Comment by freelancefrivas** [comment]
Are you sure this part is right:  "Last(events.new_credits) AS UnitPrice"? Is that the price per unit?

**Comment by darozak** [comment]
Yes. That should be correct.  You're also correct that unit price is price per unit.

**Comment by freelancefrivas** [comment]
Ok, you can take a look now: https://advolition.com/buys . I didn't add the 'GROUP BY' because it didn't seem necessary...

**Comment by darozak** [comment]
Group By is important because it ensures that we display only the most recent buy order that was placed by a specific drone for a specific resource (GROUP BY drone, resource).  For example, only the most recent buy order, which was placed by Sport at 9 AM on 14 February for Iron Ore at 5 credits, should be visible.  Although Sport wanted to buy Iron Ore for 10 credits at 8:27, the drone dropped the price to 5 credits at 9 AM, so only that should be displayed in the table.  The 8:27 order should not be shown because it is no longer valid.

I did simplify the query so it only groups by events.resouce and events.drone.  All the other groupings really were necessary:

```
SELECT Last(agents.name) AS PostedBy, Last(resources.name) AS Resource, Last(events.timestamp) AS PostedOn, Last(event_types.name) AS [Transaction], Last(events.new_credits) AS UnitPrice, Last(objects.object_name) AS Location, Last(events.new_quantity) AS MaxQuant, Last(sqInventory.Units) AS Available, Last([events].[new_quantity]-[sqInventory].[Units]) AS Volume, events.drone AS DroneID, events.resource AS ResourceID, Last(agents.object_id) AS LocationID
FROM ((((events LEFT JOIN resources ON events.resource = resources.id) LEFT JOIN agents ON events.drone = agents.agent_id) LEFT JOIN objects ON agents.object_id = objects.object_id) LEFT JOIN event_types ON events.event_type = event_types.id) LEFT JOIN sqInventory ON (events.drone = sqInventory.drone) AND (events.resource = sqInventory.resource)
WHERE (((events.event_type)=5))
GROUP BY events.drone, events.resource;
```

Also, Sport should be showing a Volume of 8 units on the table, as shown in the example at the top of this issue.  The web page currently reports the volume as -4420:

![20200216 Buy Order](https://user-images.githubusercontent.com/33500329/74697244-13758780-51c8-11ea-9f31-83ce4eefc39d.PNG)

I think you're getting -4420 because of an error in the inventory sub-query.  The sub-query needs to limit its search to only those entries that have an outcome=1, meaning the event was successfully completed.  Here is what the query should look like with the new constraint on the outcome field:

```
SELECT events.drone, events.resource, Last(events.new_quantity) AS Units
FROM events
WHERE (((events.locked)=False) AND ((events.event_type)=1 Or (events.event_type)=2) AND ((events.outcome)=1))
GROUP BY events.drone, events.resource;
```

**Comment by freelancefrivas** [comment]
Ok, I did the SQL changes you requested. I have to take your word on these as I don't fully understand some of these fields/tables...

**Comment by darozak** [comment]
This is close but not quite there yet.  I notice that in ResourceController.php you are using MAX and not  LAST to select values from the grouped field.  We really don't want the MAX values from the grouped set.  Rather we want to display the LAST (ie. most recent) values from the grouped events, assuming the events are sorted in ascending chronological order.

**Comment by freelancefrivas** [comment]
Yes, the thing is that there is FIRST() or LAST() functions in MySQL. But using MAX was wrong, it only makes sense using it with the id or time.
I found a couple of workarounds to emulate the same behavior. You should see if it works correctly now...

**Comment by freelancefrivas** [comment]
I also used one of this workarounds in the spacecraft carfo manifest table, so it would be good if you check it.

**Comment by darozak** [comment]
Thanks Fernando.  I didn't realize First() and Last() aren't supported in MySQL.  However, work-around you've implemented appears to be working!  I've played around with placing different buy orders and your table appears to be displaying the data correctly.

There are definitely some issues with the cargo manifest, but I'm not sure it has to do with any errors in your web code. I'll need to trouble shoot the cargo manifest separately to see what's going on.

As far as the displaying the buy orders are concerned, we should be able to close out this issue.

I'll post a separate issue tomorrow that deals with the creation of a page to display "Sell Orders".  The sell orders will be handled in essentially the same way as the buy orders with only a few minor differences.  Details to follow.

Thanks!
