### ISSUE TITLE
Event engine appears to lock up when spacecraft located at the Sun

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#82]
Help.  I think I broke it :(

At 11:07 AM ET I successfully moved Sport@advolition.com to the Sun:
```
<run>
0 5 perform
</run>
```
 At 11:09 AM ET I attempted to mine Iron Ore from the Sun:
```
<run>
1 perform
</run>
```
I got a fail error:
```
---- Position ----

At: Sun
Distance: 8.199748 light-minutes

---- Output ----

Protocol "Mine Iron Ore" failed
```

Subsequently simple math commands  ( like 2 3 + .) work  but all perform commands (move to, mine, etc...) result in a fail.

Checking the droplet usage states shows they spiked at 11:09 AM and haven't come down since:
![200214 Advolition Use](https://user-images.githubusercontent.com/33500329/74551867-05064200-4f22-11ea-9e42-7ee0420d13d5.PNG)

The events engine log is spewing the same error:
![200214 Event Log Capture](https://user-images.githubusercontent.com/33500329/74552172-a097b280-4f22-11ea-8d8c-d65da6f962a8.PNG)

And the stop script won't work:
![200214 Cant Stop Events Engine](https://user-images.githubusercontent.com/33500329/74552324-f704f100-4f22-11ea-9173-da99e38e8cea.PNG)

Any thoughts on what caused the events engine to derail like this?

_Originally posted by @darozak in https://github.com/Darwin-River/Ex-Machinis/issues/51#issuecomment-586381689_

**Comment by darozak** [comment]
Carlos reported that this is likely a bug which is caused be the spacecraft being located at the sun.

**Comment by crodnun** [comment]
Should be fixed now, the patch is in place and my drones have been moved to Jupiter safely.
The key here was that when we calculate the central body of any object, for the Sun obviously there is no central body, and the logic was not able to cope with this.
It was a logic bug that caused an infinite loop at the engine and the disaster we suffered.
Ready to be tested again.

**Comment by darozak** [comment]
It works!  Thanks for fixing this.
