### ISSUE TITLE
Create a page to display sell orders

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#83]
We'll need a web page to display sell orders.  This page and the underlying queries will be almost identical to those [created to display buy orders](https://github.com/Darwin-River/Ex-Machinis/issues/81). The only real differences are that:

- events.event_type=4 instead of 5.
- Volume is computed by subtracting events.new_quantity from sqInventory.Units and not the other way around.

Here is an example of what the table should look like:
![200221 Sell Order](https://user-images.githubusercontent.com/33500329/75034893-2f08b880-547c-11ea-9a0d-240cc5ca857b.PNG)

This is the SQL query that I used to generate the table:
```
SELECT Last(agents.name) AS PostedBy, Last(resources.name) AS Resource, Last(events.timestamp) AS PostedOn, Last(event_types.name) AS [Transaction], Last(events.new_credits) AS UnitPrice, Last(objects.object_name) AS Location, Last(events.new_quantity) AS MinQuantRetained, Last(sqInventory.Units) AS Available, Last([sqInventory].[Units]-[events].[new_quantity]) AS Volume, events.drone AS DroneID, events.resource AS ResourceID, Last(agents.object_id) AS LocationID
FROM ((((events LEFT JOIN resources ON events.resource = resources.id) LEFT JOIN agents ON events.drone = agents.agent_id) LEFT JOIN objects ON agents.object_id = objects.object_id) LEFT JOIN event_types ON events.event_type = event_types.id) LEFT JOIN sqInventory ON (events.drone = sqInventory.drone) AND (events.resource = sqInventory.resource)
WHERE (((events.event_type)=4))
GROUP BY events.drone, events.resource;
```

Also, for both buy and sell order tables, entries with a null or negative value in the Volume field should not be displayed.  This will need to be corrected in the buy order table as well as implemented here.

**Comment by freelancefrivas** [comment]
What happens when sqInventory returns NULL because there is no entry? Example: drone 52, resource 7. Should the inventory be processed as 0?

**Comment by freelancefrivas** [comment]
Because that's one of the cases showing null units.

**Comment by darozak** [comment]
Good point!  In the example you mention above, events.new_quantity = 20 but sqInventory.units = null because the spacecraft never obtained resource 7 (bronze pellets).  Unfortunately, 20 - null = null.  Therefore, in the case of buy orders, every time Volume = null, we should set Volume = events.new_quantity.  This case represents a drone that doesn't have bronze pellets (sqInventory.units = null) but wants to buy some.

However, null volumes in sell orders should be treated differently.  In that case the spacecraft doesn't have any bronze pellets on-board (sqInventory.units = null) but it is trying to sell some (events.new_quantity = 20).  Because the drone has nothing to sell, the volume of sell bid is effectively zero and the bid shouldn't be displayed in the sell bid table.  Who cares what you're selling something for if you have nothing to sell!

**Comment by freelancefrivas** [comment]
Ok, I did the same adjustments to this tables than I did on the cargo manifest: putting all the restrictions on the subselect that groups by.
There's nothing currently displayed in the sell orders page because it seems all the units - new_quantity results in 0 or negative at the moment...

**Comment by darozak** [comment]
The Buy Orders page looks great!  However, the Sell Orders should be showing two items now.  

For example, I just placed a sell order from Drone 52 for iron ore, with a floor of 2 units.  This means that Drone 52 will put all but 2 of its units of iron ore up for sale. 
 
![200222 Drone 52](https://user-images.githubusercontent.com/33500329/75100943-fc0d1480-55a2-11ea-9f78-08567e49c693.PNG)

Since Done 52 has 12 units in the cargo bay, the sell order volume should be 12 - 2 = 10, which it is what I'm seeing in my MS Access report:

![200222 Access Sell Orders](https://user-images.githubusercontent.com/33500329/75100886-0549b180-55a2-11ea-80c4-a232b6cbcdf7.PNG)

However, I'm still not seeing anything listed at http://advolition.com/sells.

You can similarly confirm that carlos_test is legitimately selling 9 units of iron ore if you check the event log and inventory for that drone.

Here is the query that I'm using to generate the Access report.  Assuming we can see through the use of the Last() function, it may help us guess what's going wrong with the web query. I know we're getting very close to figuring this out!

```
SELECT Last(agents.name) AS PostedBy, Last(resources.name) AS Resource, Last(events.timestamp) AS PostedOn, Last(event_types.name) AS [Transaction], Last(events.new_credits) AS UnitPrice, Last(objects.object_name) AS Location, Last(events.new_quantity) AS MinQuantRetained, Last(sqInventory.Units) AS Available, Last([sqInventory].[Units]-[events].[new_quantity]) AS Volume, events.drone AS DroneID, events.resource AS ResourceID, Last(agents.object_id) AS LocationID
FROM ((((events LEFT JOIN resources ON events.resource = resources.id) LEFT JOIN agents ON events.drone = agents.agent_id) LEFT JOIN objects ON agents.object_id = objects.object_id) LEFT JOIN event_types ON events.event_type = event_types.id) LEFT JOIN sqInventory ON (events.resource = sqInventory.resource) AND (events.drone = sqInventory.drone)
WHERE (((events.event_type)=4))
GROUP BY events.drone, events.resource
HAVING (((Last(sqInventory.Units)) Is Not Null));
```

**Comment by freelancefrivas** [comment]
Ah, yes, there was a SQL error, my fault.

**Comment by darozak** [comment]
Awesome!  This is exciting!  I'll play around with the buy and sell orders some more tomorrow and generate a bug report if anything goes wrong.  But so far, this looks great!  Thanks for your help.

**Comment by freelancefrivas** [comment]
Ok. Good to know!
