### ISSUE TITLE
Cargo manifest query needs to check for outcome=1

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#84]
The cargo manifest table, which is displayed as part of the spacecraft details page, needs to limit the underlying query to events that have an events.outcome=1.  All other events are invalid and will generate crazy cargo volumes like the one seen here for carbon ore on DroneID 52:

![200221 Cargo Manifest Error](https://user-images.githubusercontent.com/33500329/75036025-e56d9d00-547e-11ea-898f-eb6edd0b9109.PNG)

**Comment by freelancefrivas** [comment]
Ok, I added that restriction now.
What does that field represent?

**Comment by darozak** [comment]
Some events are logged by the Game Engine but blocked by the Event Engine if insufficient resources are available or some other error occurred.  If the Event Engine successfully processes an event the outcome field is set to 1.  If an error occurs, the outcome filed is assigned a negative number, which corresponds to the type of error.  

Unfortunately, now that you've applied this restriction, none of the cargo holds are displaying any resources.  However, I know that Drone ID 52 has iron ore in its cargo hold.  Could there be something wrong with how you're applying the work-around for the SQL First/Last functions?

**Comment by freelancefrivas** [comment]
Yes, sorry. I copy-pasted another line and I just realize it had ">" instead of "=".
Thanks, I understand better now.

**Comment by darozak** [comment]
It's still not working correctly.  Looking at AgentController.php, I think the problem may be that when you're choosing events_latest.id, you're not limiting the set of events to those that have an increment or decrement inventory event type (events.type= 1 or 2).  

I think you need to add this criteria to the where clause in the following join:

```
->join(DB::raw('(SELECT MAX(events.id) AS id FROM events WHERE drone = ' . $id . '  GROUP BY events.resource ORDER BY id) AS events_latest '), "events_latest.id", '=', 'events.id')//aggregation join
```
Otherwise, the latest event associated with drone $id could be something that doesn't have anything at all to do with their inventory.  Perhaps the last thing the drone did was move to another planet.

Dave

**Comment by freelancefrivas** [comment]
Yes, I think you are right. I moved all the restrictions to the subselect. I think the order was wrong too.

**Comment by darozak** [comment]
Thanks!  It seems to be working now.
