### ISSUE TITLE
The current cargo isn't displayed correctly on the spacecraft or company details page

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#85]
Right now it looks as if the current cargo always matches the max cargo on the spacecraft details page.  

![200223 Agent Details Page](https://user-images.githubusercontent.com/33500329/75116281-a1bc9400-5634-11ea-8af9-0822f1b4ae96.PNG)

However, the current cargo should be showing the total amount of cargo that is currently in the cargo bay.  This information is available by searching the events table for the most recent events with an event type of 1 or 2 and a outcome of 1.  Here's an example of the query that I use for this:

```
SELECT agents.user_id AS OwnerID, agents.agent_id AS DroneID, First(agents.name) AS DroneName, First(hulls.name) AS HullType, First(objects.object_name) AS Location, First(hulls.cargo_capacity) AS MaxCargo, First(IIf([new_cargo] Is Null,0,[new_cargo])) AS CurrentCargo, First(agents.object_id) AS LocationID
FROM ((agents LEFT JOIN events ON agents.agent_id = events.drone) LEFT JOIN hulls ON agents.hull_type = hulls.id) LEFT JOIN objects ON agents.object_id = objects.object_id
WHERE (((events.outcome)=1) AND ((events.event_type)=1 Or (events.event_type)=2))
GROUP BY agents.user_id, agents.agent_id;
```

It looks like there is a similar issue with the current cargo amounts shown in the company details page.  However, here, it always appears to show a zero.

![200223 Company Details Page](https://user-images.githubusercontent.com/33500329/75116284-aaad6580-5634-11ea-9061-ad26df400c4b.PNG)

**Comment by freelancefrivas** [comment]
Ok, I did changes to calculate that. Hope those values make sense now.

**Comment by darozak** [comment]
Nice!  Thanks for taking care of this so quickly.  

I did find one discrepancy between the cargo amounts reported in the company view and the spacecraft view.  Look at "carlos" in the following screen shots.  In the company view the cargo is listed at 40 kg.  However, in the drone view it is correctly listed as 49 kg (40 kg carbon plus 9 kg iron).

Company page for Carlos LTD:

![200223 Carlos LTD](https://user-images.githubusercontent.com/33500329/75122266-d7c83b00-5669-11ea-84f4-2047b2c0875f.PNG)

Spacecraft page for carlos:

![200223 Carlos Drone](https://user-images.githubusercontent.com/33500329/75122249-bebf8a00-5669-11ea-9b5b-c9a64a69eadb.PNG)

**Comment by freelancefrivas** [comment]
In your query your retrieve the latest increment or decrement event... but does new_cargo represent the total cargo in that case, or just one resource's cargo? I hope my question is clear...

**Comment by darozak** [comment]
The new_cargo field should contain the total mass in kg stored in the ship following the particular increment/decrement event.  In the case of drone ID 2 (above) new_cargo correctly displays the total amount of cargo in the cargo hold as 49 kg.  However, the value shown in the Carlos LTD company view is not correct.  Are you using the same query structure to get these values from new_cargo?

**Comment by freelancefrivas** [comment]
It took me a bit to figure it out, but I should have used HAVING instead of WHERE for the 'new_quantity > 0' restriction. Otherwise it filters out all events that end up in new_quantity 0, and gets the previous event for the same resource instead.
I think it works now...

**Comment by darozak** [comment]
That's good to know! It's looking much better.  

But there's still a discrepancy in what is being reported to Sport.  I'm not sure why it's showing a negative value for cargo.  The total cargo is reported correctly on the spacecraft details page.

![200225 Avalon](https://user-images.githubusercontent.com/33500329/75244934-badf5500-579a-11ea-8b08-c04df34c0e8f.PNG)

**Comment by freelancefrivas** [comment]
I'm realizing there are events affecting agent "Sport" that have new_cargo as a negative value. Look at the second one (which has outcome = 1):
![52](https://user-images.githubusercontent.com/11313913/75305953-5a95f500-5826-11ea-9ee4-b4526015a4a9.png)
You are not seeing that on the cargo manifest because of the "HAVING new_cargo >= 0". Should I do the same here?
I already did it now (I mean filtering out events where new_cargo is negative) as I think there must have been a good reason for doing that on the other query...

**Comment by darozak** [comment]
Hi Fernando.  I see what you're talking about.  The new_cargo field should never be < 0 so there must be something happening at the Event Engine, where this value is created.  Maybe Carlos (@crodnun) has some insight as to what's going on here and why the Event Engine is assigning negative values to new_cargo.

**Comment by crodnun** [comment]
Hi guys, it seems an issue at the event-engine logic. Could you share the sequence of commands you sent recently just to repeat them at my side and fix it? Thanks

**Comment by darozak** [comment]
Hi Carlos,

I'm guessing that the new_cargo value got out of sync at some point. Unfortunately, I think think the current routine, which simply adds to or subtracts from the last recorded new_cargo value is inherently unstable because if the previous value is off, every subsequent value will be off.

On the website, Fernando re-computes the total cargo from the inventory list every time it's displayed and it seems to be working very well.  See https://advolition.com/spacecraft/52 as an example.  This computation is performed by [AgentController.php](https://github.com/Darwin-River/Ex-Machinis/blob/develop/app/Http/Controllers/AgentController.php) when it derives $totalWeight.  Would it be make sense to implement a similar function in the Event Engine, when computing total cargo?

**Comment by crodnun** [comment]
Hi Dave, I am with you, that maybe we keep some corrupted entries in DB after the latest fixes, probably while I was patching issues detected you were using your drones generating new events, buggy ones.

I do not mind to use a new query, I think that is more accurate.
@freelancefrivas , could you share the exact statement that calculates the final cargo?

Maybe this?

```
SELECT agents.user_id AS OwnerID, agents.agent_id AS DroneID, First(agents.name) AS DroneName, First(hulls.name) AS HullType, First(objects.object_name) AS Location, First(hulls.cargo_capacity) AS MaxCargo, First(IIf([new_cargo] Is Null,0,[new_cargo])) AS CurrentCargo, First(agents.object_id) AS LocationID
FROM ((agents LEFT JOIN events ON agents.agent_id = events.drone) LEFT JOIN hulls ON agents.hull_type = hulls.id) LEFT JOIN objects ON agents.object_id = objects.object_id
WHERE (((events.outcome)=1) AND ((events.event_type)=1 Or (events.event_type)=2))
GROUP BY agents.user_id, agents.agent_id;
```

**Comment by freelancefrivas** [comment]
In that page what I do is add up the partial volumes for different resources.
And the query used to return them is:
`select (resources.id) as resource_id, (resources.name) as name, (events.locked) as locked, (resources.mass) as mass, (events.new_quantity) as new_quantity, (events.id) as event_id from `events` left join `resources` on `events`.`resource` = `resources`.`id` left join `event_types` on `events`.`event_type` = `event_types`.`id` inner join (SELECT MAX(events.id) AS id FROM events WHERE drone = 1 AND events.outcome = 1 AND (event_type = 1 OR event_type = 2) GROUP BY events.resource ORDER BY id DESC) AS events_latest on `events_latest`.`id` = `events`.`id` having new_quantity > 0 order by `new_quantity` desc`
It's a little complicated because it uses a subselect to group correctly.
The main idea is retrieve events of a certain _drone_, where the _outcome_ = 1 and _event_type_ is 1 or 2 (increment, decrement inventory), and finally being filtered by _new_quantity_ > 0 (I don't need to bring resources that have 0 units).

**Comment by freelancefrivas** [comment]
But as I see you're talking about the final cargo, I'm doing a simpler query to calculate that on the company page (for each drone) https://advolition.com/companies/1
`select * from `events` where `drone` = ? and `outcome` = 1 and `new_cargo` >= 0 and (`event_type` = 1 or `event_type` = 2) order by `id` desc`

**Comment by darozak** [comment]
Hi Carlos, 

Here is the code that Fernando developed to accurately compute the total cargo on the spacecraft details web page:

```
        $cargoManifest = DB::table('events')->select(DB::raw('(resources.id) as resource_id'), DB::raw('(resources.name) as name'), DB::raw('(events.locked) as locked'), DB::raw('(resources.mass) as mass')
            , DB::raw('(events.new_quantity) as new_quantity'), DB::raw('(events.id) as event_id'))
            ->leftJoin('resources', 'events.resource', '=', 'resources.id')
            ->leftJoin('event_types', 'events.event_type', '=', 'event_types.id')
            ->join(DB::raw('(SELECT MAX(events.id) AS id FROM events  WHERE drone = ' . $id . ' AND events.outcome = 1 AND (event_type = ' . EventType::TYPE_INCREMENT_INVENTORY . ' OR event_type = ' . EventType::TYPE_DECREMENT_INVENTORY . ')   GROUP BY events.resource ORDER BY id DESC) AS events_latest '), "events_latest.id", '=', 'events.id')//aggregation join
            ->orderBy('new_quantity', 'desc')->havingRaw('new_quantity >= 0')->get();
        $totalWeight = 0;
        foreach ($cargoManifest as $cargoItem) {
            if ($cargoItem->mass && $cargoItem->new_quantity)
                $totalWeight += $cargoItem->mass * $cargoItem->new_quantity;
        }
```
He basically does a database search for the most recent increment/decrement events to affect a particular resource and uses the new_quantity value from the most recent event to report how many units of a particular resource are in the cargo hold.

One important feature of this query is that it requires events.outcome = 1.  Otherwise, you risk reporting a garbage value from an unsuccessful event.

Another very important feature is the subselect clause, which allows him to pick only the most recent increment/decrement event to affect a particular resource:

```
            ->join(DB::raw('(SELECT MAX(events.id) AS id FROM events  WHERE drone = ' . $id . ' AND events.outcome = 1 AND (event_type = ' . EventType::TYPE_INCREMENT_INVENTORY . ' OR event_type = ' . EventType::TYPE_DECREMENT_INVENTORY . ')   GROUP BY events.resource ORDER BY id DESC) AS events_latest '), "events_latest.id", '=', 'events.id')//aggregation join
```
After using the $cargoManifest query to retrieve data for the cargo manifest, he uses the following script to compute the total mass for each resource (units * mass) and sum all the masses to arrive at an accurate value for the total cargo mass for the ship:

```
        $totalWeight = 0;
        foreach ($cargoManifest as $cargoItem) {
            if ($cargoItem->mass && $cargoItem->new_quantity)
                $totalWeight += $cargoItem->mass * $cargoItem->new_quantity;
        }
```

I'm guessing that you'll need to follow a similar process to compute and store the new_cargo value for recently processed events.

**Comment by darozak** [comment]
Hi Carlos, I'm handing this over to you so you can address this issue at the Event Engine when you have a chance.  Hopefully, the above explanation makes some sense.

**Comment by crodnun** [comment]
OK, I will review the maths we do behind the scenes. I think that more or less are the same. But will try to imitate the php's query.

**Comment by crodnun** [comment]
This query is in place now to calculate the cargo in a more accurate way.  Ready to be tested.

**Comment by darozak** [comment]
Unfortunately, this still isn't working correctly on the web site.  For example, the total cargo shown in http://advolition.com/spacecraft/52 (24 kg) is different from that shown for the same spacecraft (Sport) in https://advolition.com/companies/18 (1 kg).  However, I'm not sure if this is a problem with your routine or the way Fernando is constructing the query on the web page.  Unfortunately, I won't be able to trouble shoot this until I get home this evening.

**Comment by crodnun** [comment]
In my opinion and in order to solve any other bug, we should clean the events table and generate new ones.
Some of the entries are incorrect, as I was developing and fixing things at the same time you were creating the web part. I did not remove any entry there to let Fernando test it and make progress.
Do you agree? It will be easier to start from scratch, generating new events and debug any new issue there. I know for sure that there are many corrupted entries there.

**Comment by freelancefrivas** [comment]
That's fine by me.

**Comment by darozak** [comment]
Ok.  That makes sense.

**Comment by darozak** [comment]
I've been trying to figure out what's going on with the new_cargo field by adding and removing different items from my Sport drone's cargo bay and watching how new_cargo changes in the DB.  It looks like new_cargo is currently recording the change in the resource while new_quantity tracks the total amount of the resource (as it should). 

Here is what I'm seeing in the events table as I mine iron ore on 6 March ( 1 1 perform -> + 12 units = 18 units ), and again on 10 March ( 1 1 perform -> +12 units = 30 units. I then mine carbon ore with nothing already in cargo ( 1 2 perform -> + 21 units = 21 units ) and dump 6 units of iron ore ( 6 4 perform -> -6 units = 24 units ).

![200310 Sport Events](https://user-images.githubusercontent.com/33500329/76310798-e3407680-62a5-11ea-8b62-ec147342e412.PNG)

The new_cargo field should be summing the current mass of all the cargo contained in the ships cargo hold.  As you can see below, this is working correctly in https://advolition.com/spacecraft/52 using Fernando's coding.  We just need to replicate this algorithm in the Game Engine whenever it recomputes new_cargo.

![200310 Sport Cargo Manifest](https://user-images.githubusercontent.com/33500329/76311099-94dfa780-62a6-11ea-96f8-1e44efced91e.PNG)

**Comment by darozak** [comment]
Reviewing event log for drones Sport (ID=52) and Speed (ID=53), the Event Engine does not appear to be discovering any of the resources that are already in the cargo hold when tallying the current cargo mass.

The following is just one of several examples from the event log where it queries the drone's resources but apparently doesn't find anything even though the webpage query is showing that Drone 52 has iron ore, carbon ore, and iron pellets in its cargo:

```
* 11/03/2020,11:24:40.942 [0] Getting resources for droneID [52]
* 11/03/2020,11:24:40.942 [0] Running query [select  resources.id as resource_id, resources.name as name, events.locked as locked, resources.mass as mass, events.new_quantity as new_quantity, events.id as event_id  from events left join resources on events.resource = resources.id  left join event_types on event_types.id = events.event_type  join (select max(events.id) as id from events where drone = 52 and events.outcome = 1 and events.outcome = 0 and (events.event_type = 1 or events.event_type = 2) group by events.resource ORDER BY id DESC) as events_latest on events_latest.id = events.id   ORDER BY new_quantity;]
* 11/03/2020,11:24:40.943 [0] Adding current event cargo [-20] to [0]
```

According to src/db_e.c the function db_get_drone_resources is supposed to be logging whenever the query locates a resource event.  However, it isn't logging anything after the query.  It just reports that it's adding the current event to an already empty cargo bay.

**Comment by crodnun** [comment]
Hi Dave, sorry for the delay. I could not review this till today (covid19 in Spain ... you know, many issues). God thanks, for the moment, not at my family but we are living in a  kind of "state of paranoia".

I have detected the issue and fixed at the server, feel free to test it again and share results.

The root cause was an extra condition I added at Fernando's query, that I need at the events engine (Fernando does not need it because he is not manipulating at the same time the events, but events engine needs to take into account also current event (outcome = 0))

If you look at the query:

```
* 11/03/2020,11:24:40.942 [0] Running query [select  resources.id as resource_id, resources.name as name, events.locked as locked, resources.mass as mass, events.new_quantity as new_quantity, events.id as event_id  from events left join resources on events.resource = resources.id  left join event_types on event_types.id = events.event_type  join (select max(events.id) as id from events where drone = 52 and events.outcome = 1 and events.outcome = 0 and (events.event_type = 1 or events.event_type = 2) group by events.resource ORDER BY id DESC) as events_latest on events_latest.id = events.id   ORDER BY new_quantity;]
```

I put there by mistake this condition (lol):

```
and events.outcome = 1 and events.outcome = 0
```

And should be a logic OR:

```
and (events.outcome = 1 or events.outcome = 0)
``` 

If you run the query now for your drones you should obtain now better results, let's see if this improves, otherwise just ping me here and I will review it again.

For drone=52 

```
mysql> select  resources.id as resource_id, resources.name as name, events.locked as locked, resources.mass as mass, events.new_quantity as new_quantity, events.id as event_id  from events left join resources on events.resource = resources.id  left join event_types on event_types.id = events.event_type  join (select max(events.id) as id from events where drone = 52 and (events.outcome = 1 or events.outcome = 0) and (events.event_type = 1 or events.event_type = 2) group by events.resource ORDER BY id DESC) as events_latest on events_latest.id = events.id   ORDER BY new_quantity;
+-------------+---------------+--------+------+--------------+----------+
| resource_id | name          | locked | mass | new_quantity | event_id |
+-------------+---------------+--------+------+--------------+----------+
|           1 | Ore, Iron     |      0 |    1 |            4 |      237 |
|           2 | Pellets, Iron |      0 |    1 |            5 |      193 |
|           3 | Ore, Carbon   |      0 |    1 |           21 |      233 |
+-------------+---------------+--------+------+--------------+----------+
```

And for drone=53:

```
mysql> select  resources.id as resource_id, resources.name as name, events.locked as locked, resources.mass as mass, events.new_quantity as new_quantity, events.id as event_id  from events left join resources on events.resource = resources.id  left join event_types on event_types.id = events.event_type  join (select max(events.id) as id from events where drone = 53 and (events.outcome = 1 or events.outcome = 0) and (events.event_type = 1 or events.event_type = 2) group by events.resource ORDER BY id DESC) as events_latest on events_latest.id = events.id   ORDER BY new_quantity;
+-------------+-------------+--------+------+--------------+----------+
| resource_id | name        | locked | mass | new_quantity | event_id |
+-------------+-------------+--------+------+--------------+----------+
|           3 | Ore, Carbon |      0 |    1 |           21 |      224 |
|           1 | Ore, Iron   |      0 |    1 |           31 |      236 |
+-------------+-------------+--------+------+--------------+----------+
2 rows in set (0.00 sec)
```

**Comment by darozak** [comment]
Hi Carlos.  Things are getting a bit crazy here as well with the virus.  I'm glad to hear your family is well. Stay safe and healthy!

It looks like you found the problem with the query!  Unfortunately the values still aren't coming out right.  And it looks like this is because you're using the unprocessed current event when tallying the cargo mass.  Here's a portion of the event log that's produced when I try to dump two units of iron ore ( 2 4 perform):

```
* 13/03/2020,11:26:09.569 [0] Running query [select  resources.id as resource_id, resources.name as name, events.locked as locked, resources.mass as mass, events.new_quantity as new_quantity, events.id as event_id  from events left join resources on events.resource = resources.id  left join event_types on event_types.id = events.event_type  join (select max(events.id) as id from events where drone = 52 and (events.outcome = 1 or events.outcome = 0) and (events.event_type = 1 or events.event_type = 2) group by events.resource ORDER BY id DESC) as events_latest on events_latest.id = events.id   ORDER BY new_quantity;]
* 13/03/2020,11:26:09.570 [0] Resource found ID [1] NAME [Ore, Iron] LOCKED [0] MASS [1] QUANTITY [-2] EVENT_ID [238] for DRONE_ID [52]
* 13/03/2020,11:26:09.570 [0] Resource found ID [2] NAME [Pellets, Iron] LOCKED [0] MASS [1] QUANTITY [5] EVENT_ID [193] for DRONE_ID [52]
* 13/03/2020,11:26:09.570 [0] Resource found ID [3] NAME [Ore, Carbon] LOCKED [0] MASS [1] QUANTITY [21] EVENT_ID [233] for DRONE_ID [52]
* 13/03/2020,11:26:09.570 [0] Adding resource [Pellets, Iron], quantity [5], mass [1] to new_cargo, total now [5]
* 13/03/2020,11:26:09.570 [0] Adding resource [Ore, Carbon], quantity [21], mass [1] to new_cargo, total now [26]
* 13/03/2020,11:26:09.570 [0] Adding current event cargo [-2] to [26]
```

You don't need to do anything just yet.  I'll try to run down the error and identify the issue.  I'm getting more familiar with the code and this will be good practice for me!

**Comment by darozak** [comment]
Fixed!  The Engine Engine appears to be computing total cargo correctly now.  The solution was to only consider events with outcome = 1 (and not outcome = 0) in the cargo mass calculation.
