### ISSUE TITLE
New error when mining ores

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#86]
On multiple occasions I've tried to mine  iron ore using Drone 52, which is located at Earth.  The drone only has 12 units of iron ore in its cargo hold so it should have plenty of room for more.

Whenever I submit the command ("1 perform") to mine iron ore, I get an email response which says the activity was successfully completed.  However, when I check the events table, the event outcome indicates and error (-3) and the quantities of ore are far above what they should be, often between 2000 and 3000 units.

This started happening on 15 February.  Prior to that I was able to mine ore without any trouble.

![200223 Mining Events](https://user-images.githubusercontent.com/33500329/75116469-b13cdc80-5636-11ea-8a10-940c464ee2e9.PNG)

**Comment by crodnun** [comment]
Hi Dave, I have studied this bug and share here my conclusions (seems that you are not using correctly the command or just my misunderstanding interpreting protocols and logic).

This is what I have detected, at protocols table we have the following entries right now:

```
mysql> select * from protocols;
+----+-----------------+------------+---------------+-----------------------------------------------------------------------------------------------------------+------------+------------+------------+
| id | name            | parameters | bulk_modifier | description                                                                                               | observable | reportable | multiplier |
+----+-----------------+------------+---------------+-----------------------------------------------------------------------------------------------------------+------------+------------+------------+
|  1 | Mine Iron Ore   |          0 |           100 | 1 perform | Adds 1 unit of iron ore to your drone's cargo hold.                                           |          1 |          1 |          1 |
|  2 | Mine carbon ore |          0 |           100 | 2 perform | Adds 10 units of carbon ore to your inventory.                                                |          1 |          1 |          1 |
|  3 | Smelt iron ore  |          0 |           100 | 3 perform | Converts one unit of iron ore to one unit of refined iron pellets.                            |          1 |          1 |          1 |
|  4 | Dump Iron Ore   |          0 |           100 | 4 perform | Dumps 10 units of iron ore from your cargo hold.                                              |          1 |          1 |          1 |
|  5 | Move to X       |          0 |           100 | N1 5 perform | Moves the spacecraft to the the astronimical object whoes ID is N1.                        |          1 |          1 |          0 |
|  6 | Move to Jupiter |          0 |           100 | 6 perform | Moves the spacecraft to Jupiter.                                                              |          1 |          1 |          0 |
|  7 | Sell Resource   |          3 |           100 | [P M R 7 perform]: Places order to sell resource R at price P, keeping min M units at drone's cargo hold. |          1 |          1 |          0 |
|  8 | Buy Resource    |          3 |           100 | [P M R 8 perform]: Places order to buy resource R at price P, keeping max M units at drone's cargo hold.  |          1 |          1 |          0 |
+----+-----------------+------------+---------------+-----------------------------------------------------------------------------------------------------------+------------+------------+------------+
```

If you look at the latest field, "multiplier". The logic interprets this flag (when 1) as a multiplier that must be read from the stack.  When is not supplied we get rubbish from the stack, exactly at your latest tests, we got a value of 234, that it is used as a multiplier for the quantities:

These are the logs I could review:

```
* 23/02/2020,17:07:54.568 [0] NAME [Mine Iron Ore] DESCRIPTION [1 perform | Adds 1 unit of iron ore to your drone's cargo hold.] BULK_MODIFIER [100] OBSERVABLE [1] REPORTABLE [1] MULTIPLIER [1] obtained for PROTOCOL_ID [1]
* 23/02/2020,17:07:54.568 [0] Action [235, 52, 1, 1, 0] inserted into DB
* 23/02/2020,17:07:54.568 [0] [0] parameters succesfully read from stack for protocol ID [1]
* 23/02/2020,17:07:54.568 [0] Multiplier set to [234] for protocol [1]
* 23/02/2020,17:07:54.569 [0] Running query [SELECT * FROM resource_effects WHERE protocol = 1]
* 23/02/2020,17:07:54.569 [0] Resource effect found ID [1] DRONE [0] RESOURCE_ID [1] EVENT_TYPE [1] LOCAL [1] INSTALLED [0] LOCKED [0] DEPLETE [0] QUANTITY [1] TIME [0] for PROTOCOL_ID [1]
* 23/02/2020,17:07:54.569 [0] Processing resource effect ID [1] DRONE [0] RESOURCE_ID [1] EVENT_TYPE [1] LOCAL [1] INSTALLED [0] LOCKED [0] DEPLETE [0] QUANTITY [1] TIME [0] for PROTOCOL_ID [1] MULTIPLIER [234]
```

Notice that we got a 234 value to use as a multiplier (something present at the stack at this moment).

And we inserted this entry in DB:

```
* 23/02/2020,17:07:54.570 [0] Query [INSERT INTO events (event_type, action, logged, outcome, drone, resource, installed, locked , new_quantity, new_cargo) VALUES(1, 235, 1, 0, 52, 1, 0, 0, 234, 234  )] executed
```

New quantity= 234,  new_cargo = 234

So we are using huge multipliers to deal with quantities this way.

Reviewing my tests, I normally use this protocol as follows:

```
<run>1 1 perform</run> 
```

Apart, we have another table that provides multipliers, abundancies table:

```
mysql> select * from abundancies;
+----+----------+----------+------------+
| id | location | resource | multiplier |
+----+----------+----------+------------+
|  1 |        3 |        1 |         12 |
|  2 |        0 |        8 |         10 |
|  3 |        0 |        1 |         20 |
|  4 |        1 |        1 |          1 |
|  5 |        1 |        3 |          4 |
|  6 |        3 |        3 |         21 |
|  7 |        3 |        5 |          4 |
+----+----------+----------+------------+
7 rows in set (0.00 sec)
```

Depending on the location and resource, we right now multiply the requested quantity by this new multiplier (latest column above). 

The point that describes the same is this at docs:

```
Whenever the EE processes a harvest event (events.event_type = 1), the it multiplies the events.new_quantity value by the abundancies.multiplier value for the first entry in the abundancies table with the same drone location and resource values as indicated by the event. If a matching entry is not found in the table, events.new_quantity is set to zero, indicating that the resource cannot be harvested from that location.
```

All these multipliers are applied to the initial quantity and have a max limit, the max cargo supported by the hull type, at my drones just 50 units. So using so big multipliers will lead to errors most of the times (outcome -3).

So it is just a matter of clarifying how you would like to work with the same and maybe configuring the DB according to the desired behaviour.

Let me know if all this is correct, or is there something we need to refactor/change.

**Comment by darozak** [comment]
Oh wow.  I feel stupid! I completely forgot about the process multiplier!  That makes so much sense.  I also forgot about the logs as a trouble-shooting tool.  Thanks for your detailed account.  I've leaned a lot from this mistake :)

One point that comes to mind.  You mention that drones can't exceed the capacities of their cargo holds.  That's correct.  However, you list this capacity in terms of units.  This limit is actual in terms of maximum mass (kg).  

Every resource has a mass (resources.mass).  In the case of iron ore, 1 unit of ore = 1 kg.  However, other materials may weigh more. For example, the mass of an extruder (ID=12) is 10 kg.  Therefore, you could only add 5 extruders to your cargo because 5 units x 10 kg = 50 kg, which is the maximum capacity of your cargo hold.  

Does the current logic account for the fact that some units will weigh more than others when determining whether there is enough room for them in the cargo hold?

Also, is mass taken into account when you recompute events.new_cargo?  I'm worried that you may be computing new_cargo in terms of unit counts rather than total mass (units * kg).

**Comment by crodnun** [comment]
I take the mass into account in the maths I do to calculate the new_cargo when inserting a new event:

```
 newEvent.new_cargo = (newEvent.new_quantity * resource.resource_mass); // here we reflect the change in mass units
```

The pity is that the mass for every protocol is 1, at least at the protocols we have defined so far.

So the units and kgs are the same so far at our protocols, tests.

Maybe it is a good moment to define a new protocol to work with other resources (whose mass != 1) and check if it works as intended, but as far as I see, we treat it in our calculations.

**Comment by darozak** [comment]
Perfect!  I'll change up the unit masses and play-test this feature.  I'll post a separate issue if I uncover anything.
