### ISSUE TITLE
Construct a resource details page

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#88]
We still need to create a web page that displays the details of a particular resource.  This page will contain the following components:
- Resource name (title)
- Resource ID
- Unit mass in kg
- Resource description (resources.description)
- A table that displays the top 10 buy orders associated with the resource, sorted in order of descending price.
- A table that displays the top 10 sell orders associated with the resource, sorted in order of increasing price.
- The buy and sell orders should also be sortable by volume and searchable by location.  Drones and location names will be hyperlinked to the related details pages.

**Comment by darozak** [comment]
Hi Fernando. I see that you've created resource pages that give the ID, mass, and description of specific resources.  Will it be possible to show resource-specific buy/sell orders as well?

**Comment by freelancefrivas** [comment]
Yes, I'm still working on it. Do you want to display the status for each order? Would that be the outcome? Or filter by that?

**Comment by freelancefrivas** [comment]
And another question: when you talk about searching by location, does that mean the object_id field in the agents table? I don't think it's new_location...

**Comment by darozak** [comment]
The idea is to exactly reproduce the http://advolition.com/buys and http://advolition.com/sells tables on the resource details page.  The only difference is that you will limit displayed orders to those involving the specific resource.  For example, the iron ore resource page (http://advolition.com/resources/1) would only show buy and sell orders related to iron ore.

**Comment by freelancefrivas** [comment]
Sorry, but I think I'm having another problem... or else I have the concepts wrong. When I have to calculate the volume, I use new_quantity - sqInventory.units (or vice-versa)... but in sqInventory I only have the current ships inventory. How can I know how much really was exchanged when that operation happened?
I think this problem doesn't happen with the previous queries...

**Comment by freelancefrivas** [comment]
Or is it that you want to group by agent here too, and only bring the last buy/sell operation? But even then... there is a problem too. What happens if there was one of each, a buy and a sell event for the same agent?

**Comment by freelancefrivas** [comment]
Don't you think it would be better to just store the volume in the event, or another table associated with it?

**Comment by darozak** [comment]
Hi Fernando.  Let me try to answer your questions here:

Buy and sell order events don't actually represent an exchange of money and resources.  They only represent the request to do so.  They're kind of like items being offered for sale on Ebay.  They represent the offer and not the actual transaction.

With respect to buy orders, volume represents the difference between what the drone currently has in its cargo bay and the amount of resource it wants to have in its cargo bay.  While the market order will remain constant, the volume (what the drone is really willing to pay for) will change whenever the done adds or removes the resource from its cargo bay.  Since volume is dependent on the buy order and the current inventory, both of which can change independent of one another, it would be difficult to store volume as an event field.  It's easier to recompute it whenever needed.  The same is true for sell orders.

Yes. You do need to group by agents here as well and only grab the most recent market order for a particular agent and resource.  These queries should be identical to the ones you run on http://advolition.com/buys and http://advolition.com/sells.  The only difference will be that the searches will be limited to the resource that is being dealt with on the resource details page.

Buy and sell orders should be dealt with seprately.  There sill be one table for displaying buy orders and another for showing sell orders.  They will be seperate queries just like they are in http://advolition.com/buys and http://advolition.com/sells

**Comment by freelancefrivas** [comment]
Ok, David. Thanks for taking the time to clarify that. I understand better the intentions now. I will use the same query then.

**Comment by darozak** [comment]
That would be great. Thanks for your help with this!

**Comment by freelancefrivas** [comment]
No problem! Ok, you can take a look now...

**Comment by darozak** [comment]
Nice job! This is perfect! Thank you..
