### ISSUE TITLE
Mod the resource effects table to accept negative values

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#89]
The resource effects table needs to be capable of accepting negative values in fields in the drone and resource fields.  This is because negative values are used to identify the fields as accepting variable player-specified quantities rather than constants.

**Comment by freelancefrivas** [comment]
Ok, I set those columns as signed. Also adjusted the bytes assigned, which I don't think were right...

**Comment by darozak** [comment]
Thanks Fernando.  We'll never be storing values in these fields greater than +/- 65535 (i.e. FFFF plus one bit for the sign).

Dave

**Comment by darozak** [comment]
I modified [game-engine/sql/create_db.sql](https://github.com/Darwin-River/Ex-Machinis/commit/53f85565069791b8672704a294fe9d1bef9ce487) to account for signed fields in the resource_effects table.

**Comment by freelancefrivas** [comment]
Are the database changes registered there?
Should I update that file every time I make a database structure change?

**Comment by darozak** [comment]
Yes. That will ensure db edits are permanent.On Mar 3, 2020 11:15 AM, Fernando Rivas <notifications@github.com> wrote:Are the database changes registered there?
Should I update that file every time I make a database structure change?

**Comment by freelancefrivas** [comment]
Mm I now think about the changes that I did previously and didn't register... (mostly indexes and foreign keys)

**Comment by freelancefrivas** [comment]
Do you want me to compare this file with a current dump to add any key/index that may be missing?

**Comment by darozak** [comment]
Yes please.  That way we'll be sure we won't lose these updates.On Mar 4, 2020 11:28 PM, Fernando Rivas <notifications@github.com> wrote:Do you want me to compare this file with a current dump to add any key/index that may be missing?
