### ISSUE TITLE
Game Engine needs to support variable drone and resource IDs.

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#90]
Hi Carlos,

I tried to create a new procedure (9), which allows a drone to transfer 1 unit of iron ore to another drone.  The procedure works by depleting 1 unit of ore from the acting drone and incrementing the amount of iron ore in the recipient drone.   

In order for this protocol to work, the user needs to specify the ID of the recipient drone as a parameter on the stack.  I set **protocol.parameters** to 1 and **resource_effects.drone** to -1 for the increment event.  This should trigger the Game Engine to pull one value from the stack and insert it into the events table entry in place of the -1 for drone ID.  

When looking through **src/protocol.c**, it looks like you capture this value from the stack in **protocol->parameters[i]** but never search for and replace negative values with the corresponding stack variable in **protocol_process_resource_effect**.  

I believe **protocol_process_resource_effect** needs a clause which checks for negative values in **resource_effects.drone** and replaces it with the corresponding stack item (-1 = protocol->parameters[0], -2 = protocol->parameters[1], etc...).

I think this should be a simple fix but am not yet confident enough in the script to implement myself.  Can you take a look?

**Comment by crodnun** [comment]
Hi Dave, yes probably this part is not supported yet or never taken into account. We started with a simple approach with some examples you provided. I am pretty sure that never implemented as we never could test it before, lol.  Now that we have in place some protocols to do the same, I am with you what it should be a quick fix. I will take care of this, no worries.

**Comment by crodnun** [comment]
Hi Dave, I have added some changes to take this into account (at least to insert the 2 events you expected), but with this new logic, new problems arise when we generate a couple of events for the same action. 

This is what I have detected:

At current logic, it can happen that one of the events within the transfer goes OK but the other fails because one drone can do the depletion but the other has no room for the new cargo.

How you would like to proceed with these new scenarios?

Example:

At my example, once fixed the codes, 2 new events are inserted. The first fails as we do not have this resource, but the second goes OK, as we have room to add this cargo.

```
| 210 |          2 |    260 |      1 |      -3 |     1 |        1 |         0 |      0 |          300 |        NULL |         NULL |             NULL |       299 | 2020-03-02 18:45:25 |
| 211 |          1 |    260 |      1 |       0 |     2 |        1 |         0 |      0 |          259 |        NULL |         NULL |             NULL |       259 | 2020-03-02 18:45:25 |
+-----+------------+--------+--------+---------+-------+----------+-----------+--------+--------------+-------------+--------------+------------------+-----------+---------------------+
````

**Comment by darozak** [comment]
Thanks Carlos!  For now, the sending drone will simply loose the cargo. It will be successfully depleted from their cargo hold but blocked from being added to the cargo hold of the recipient drone and consequently be lost in space! BTW, we'll also need to implement the same sort of variable check with drone ID since ideally the user will specify both the resource and the destination spacecraft for the transfer protocol. On Mar 2, 2020 1:53 PM, Carlos Rodriguez Nuñuez <notifications@github.com> wrote:Hi Dave, I have added some changes to take this into account (at least to insert the 2 events you expected), but with this new logic, new problems arise when we generate a couple of events for the same action.
This is what I have detected:
At current logic, it can happen that one of the events within the transfer goes OK but the other fails because one drone can do the depletion but the other has no room for the new cargo.
How you would like to proceed with these new scenarios?
Example:
At my example, once fixed the codes, 2 new events are inserted. The first fails as we do not have this resource, but the second goes OK, as we have room to add this cargo.
| 210 |          2 |    260 |      1 |      -3 |     1 |        1 |         0 |      0 |          300 |        NULL |         NULL |             NULL |       299 | 2020-03-02 18:45:25 |
| 211 |          1 |    260 |      1 |       0 |     2 |        1 |         0 |      0 |          259 |        NULL |         NULL |             NULL |       259 | 2020-03-02 18:45:25 |
+-----+------------+--------+--------+---------+-------+----------+-----------+--------+--------------+-------------+--------------+------------------+-----------+---------------------+

**Comment by crodnun** [comment]
Hi Dave, no problem at all with resource_id. With my latest change, I already took this into account, we have support for: drone_id, resource_id, and even quantity. The 3 can be pulled from the stack now, just using the suitable value: -1, -2, -3.

One more question, what would happen in this scenario?

The first drone do not have resources to transfer, but the second has room to accept them. We will need to protect also this scenario somehow, as they are inserted as independent events in DB.
We could have here a "hole", somebody transferring resources that do not have, lol

**Comment by darozak** [comment]
I plan to protect against this possibility by designing protocols so that depletion events always occur before increment events.  This will work because the Event Engine should be aborting an action[ as soon as it encounters a failed event](https://github.com/Darwin-River/Ex-Machinis/blob/develop/documents/mechanics.md#the-event-engine):

> If any of these errors are detected, the EE will update the event’s outcome with the indicated value and flag the corresponding action in the action table as aborted.

So, if the player tries to ship resources that the drone doesn't have, the Event Engine will block the depletion event, flag the action as being aborted, and automatically ignore any future events associated with this action.

**Comment by darozak** [comment]
Carlos, I tested variable IDs and it appears to be working!  Thanks for helping.
