### ISSUE TITLE
When transferring materials between ships, the Event Engine incorrectly applies the abundancies multiplier

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#92]
When I transferred one unit of iron ore to another ship in Earth's orbit, twelve units of ore were added to the receiving ships cargo bay! I discovered that this is because we designed the Event Engine to apply the abundancy multiplier to all increment events (event_type = 1).  

>The abundancies table is used to record the availability of harvestable resources at different locations. Whenever a harvest event occurs (events.event_type = 1), the Event Engine multiplies the events.new_quantity value by the abundancies.multiplier value for the first entry in the abundancies table with the same drone location and resource values as indicated by the event.

This needs to be fixed.  We need to distinguish between harvest events and standard increment events.  I'll need to think of the best way to do this.

**Comment by darozak** [comment]
I think the best thing to do will be to create a Boolean field in the event_effects table that indicates when the abundancies multiplier should be applied,

**Comment by crodnun** [comment]
Do you want me to modify the database model to accommodate the same? 
I envisage the following changes:
1) Add boolean at resource_effects to compute abundancies or not

See table below (new field; 'abundancies').
```
mysql> desc  resource_effects ;
+------------+---------------------+------+-----+---------+-------+
| Field      | Type                | Null | Key | Default | Extra |
+------------+---------------------+------+-----+---------+-------+
| id         | int(5) unsigned     | NO   | PRI | NULL    |       |
| drone      | int(11)             | YES  |     | NULL    |       |
| resource   | int(11)             | YES  |     | NULL    |       |
| protocol   | int(5) unsigned     | YES  | MUL | NULL    |       |
| event_type | int(2) unsigned     | YES  |     | NULL    |       |
| local      | tinyint(1) unsigned | NO   |     | 0       |       |
| installed  | tinyint(1) unsigned | NO   |     | 0       |       |
| locked     | tinyint(1) unsigned | NO   |     | 0       |       |
| deplete    | tinyint(1) unsigned | NO   |     | 0       |       |
| abundancies| tinyint(1) unsigned | NO   |     | 0       |       |
| quantity   | int(5) unsigned     | YES  |     | NULL    |       |
| time       | int(5) unsigned     | YES  |     | NULL    |       |
+------------+---------------------+------+-----+---------+-------+
11 rows in set (0.00 sec)
```

2) Modify the logic to read this new field and take it into account. When disabled, do not apply abundancies there.

3) Last but not least, update the documentation, adding this new field and its logic description.

Let me know if I am correct.

**Comment by darozak** [comment]
Yes. This sounds good. Thanks for addressing this issue.On Mar 3, 2020 4:22 PM, Carlos Rodriguez Nuñuez <notifications@github.com> wrote:Do you want me to modify the database model to accommodate the same?
I envisage the following changes:
Add boolean at resource_effects to compute abundancies or not
See table below (new field; 'abundancies').
mysql> desc  resource_effects ;
+------------+---------------------+------+-----+---------+-------+
| Field      | Type                | Null | Key | Default | Extra |
+------------+---------------------+------+-----+---------+-------+
| id         | int(5) unsigned     | NO   | PRI | NULL    |       |
| drone      | int(11)             | YES  |     | NULL    |       |
| resource   | int(11)             | YES  |     | NULL    |       |
| protocol   | int(5) unsigned     | YES  | MUL | NULL    |       |
| event_type | int(2) unsigned     | YES  |     | NULL    |       |
| local      | tinyint(1) unsigned | NO   |     | 0       |       |
| installed  | tinyint(1) unsigned | NO   |     | 0       |       |
| locked     | tinyint(1) unsigned | NO   |     | 0       |       |
| deplete    | tinyint(1) unsigned | NO   |     | 0       |       |
| abundancies| tinyint(1) unsigned | NO   |     | 0       |       |
| quantity   | int(5) unsigned     | YES  |     | NULL    |       |
| time       | int(5) unsigned     | YES  |     | NULL    |       |
+------------+---------------------+------+-----+---------+-------+
11 rows in set (0.00 sec)


Modify the logic to read this new field and take it into account. When disabled, do not apply abundancies there.

Last but not least, update the documentation, adding this new field and its logic description.

Let me know if I am correct.

**Comment by crodnun** [comment]
This change is in place now, logic and SQL model updated.

At server we have now this table:

```
mysql>  select * from resource_effects;
+----+-------+----------+----------+------------+-------+-----------+--------+---------+-------------+----------+------+
| id | drone | resource | protocol | event_type | local | installed | locked | deplete | abundancies | quantity | time |
+----+-------+----------+----------+------------+-------+-----------+--------+---------+-------------+----------+------+
|  1 |     0 |        1 |        1 |          1 |     1 |         0 |      0 |       0 |           1 |        1 |    0 |
|  2 |     0 |        3 |        2 |          1 |     0 |         0 |      0 |       0 |           1 |        1 |    0 |
|  3 |     0 |        1 |        3 |          2 |     0 |         0 |      0 |       1 |           0 |        1 |    0 |
|  4 |     0 |        2 |        3 |          1 |     0 |         0 |      0 |       0 |           0 |        1 |   10 |
|  5 |     0 |        1 |        4 |          2 |     0 |         0 |      0 |       1 |           0 |        1 |    0 |
|  6 |     0 |        1 |        9 |          2 |     0 |         0 |      0 |       0 |           0 |        1 |    0 |
|  7 |    -1 |        1 |        9 |          1 |     0 |         0 |      0 |       0 |           0 |        1 |    0 |
+----+-------+----------+----------+------------+-------+-----------+--------+---------+-------------+----------+------+
7 rows in set (0.00 sec)
```

Notice that only protocols 1 and 2 have the abundancies flag enabled, so they will apply a multiplier to the quantity, the rest of rows do not apply the abundancies multiplier depending on location.

**Comment by darozak** [comment]
Perfect.  Thanks for making this change.
