### ISSUE TITLE
Different charsets across the database

### ISSUE THREAD

**Issue by freelancefrivas** [Darwin-River/Ex-Machinis#94]
I noticed tables have different charsets/collations set. Some of them are utf8mb4 and some are utf8. Can we put them all in the same charset? I'm having problems now while joining tables of different charsets. Have no idea why it didn't happen before though...
If so, do you have any preference over which one to use?

**Comment by crodnun** [comment]
Hi Fernando, 
Moved everything to:
DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
I see utf8mb4 as a superset of utf8, so I prefer this.
Ping me here if any issue arises after these changes.

DB creation script also updated with this at repository.

**Comment by darozak** [comment]
Thanks for catching and fixing.
