### ISSUE TITLE
Allow protocols and queries web pages to be filtered by URL

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#95]
Sometimes I want to point the user to a specific protocol or query on the http://advolition.com/protocols or http://advolition.com/queries page.  Would it be possible to mod these pages so I can optionally include a filter term in the url (for example, "http://advolition.com/protocos?iron") that will automatically filter the table contents as if I had manually entered the term ("iron") in the "filter by keyword" field at the top of the table?

**Comment by freelancefrivas** [comment]
Ok, I'll get the keyword from the url.

**Comment by freelancefrivas** [comment]
You can try it now using ?keyword= and see if that's good enough...

**Comment by darozak** [comment]
Nice! Thanks so much.
