### ISSUE TITLE
Action time delays do not appear to be working

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#96]
I just created two new protocols which allow drones to push (11) or pull (10) resources to or from another ship.  Each protocol allows the user to specify which ship and resource will be targeted by the action and this is working perfectly!

However, I also programmed in a 5 minute delay between the times of the depletion event and the increment event to represent the time it takes to actually transfer the materials.  I did so be setting resource_effects.time = 5 for the increment event.

If all were working correctly, I would see the depletion event take place immediately.  However, the increment event wouldn't be processed by the Event Engine until five minutes later.  Unfortunately, this doesn't appear to be the case, with both events occurring at the same time.

We need to troubleshoot and fix this bug.

**Comment by crodnun** [comment]
Hi Dave, just one comment. This was not implemented before, lol, so its status is just "not implemented". We never talk about the same in our approach to protocols (we started with very simple ones, remember...), so just in case you want to play around, take this into account. No bug to fix there, just missing to decide what should be the engine's behaviour for these scenarios.

**Comment by darozak** [comment]
Thanks Carlos.  I suspected that was the case but wasn't thinking when I flagged it as a bug.  I think this should be a fairly straightforward implementation but I shout out if I get stuck.

**Comment by darozak** [comment]
Hi Carlos, I notice that you're using the time_t type def for the timestamp in the events table. Does time_t encode time in seconds since 1 Jan 1970?  That appears to be the standard convention.

**Comment by crodnun** [comment]
Yes, Dave, this is one of the standard ways to deal with times in C. You are correct

To get current time you can invoke this function:

```
time_t now = time(NULL);
```
And then play around with maths, add, substract, etc,... always dealing with seconds

**Comment by darozak** [comment]
Thanks!  Does MySQL store dates using the same convention?

**Comment by crodnun** [comment]
Well, mysql uses a different approach, but you have many functions to convert to/from C time_t type into Mysql DATETIME() type.

Example:

```
INSERT INTO xxxxxx (file_id, image_dir, modification_time,last_updated_by) SELECT file_id, '/opt/insiteone/images/PHAH00', FROM_UNIXTIME(1508240128), 'jbNotify' FROM vna.files WHERE image_proxy_name='PHAH0006.118';
```

The previous query inserts a time_t value into DB using the function FROM_UNIXTIME(), there is another to do the opposite:  UNIX_TIMESTAMP(date_here).

**Comment by darozak** [comment]
Awesome.  I used DATE_ADD to successfully add the resource_effect time delay to the new event.  Unfortunately, it appear that the Event Engine processes all new events, even if they occur at some future time point.  So, half the problem is solved!  Now I'll look into what is happening at the Event Engine.

**Comment by crodnun** [comment]
Yes this is just another query here:

https://github.com/Darwin-River/Ex-Machinis/blob/bbe7f2aa662eada4b7291397dfbeda79ba3dae41/game-engine/src/db_e.c#L294-L401

This query gets all the events to be processed by the event engine, you should add there more filters to get only those that must happen right now.

**Comment by darozak** [comment]
Thanks Carlos!  That was an easy fix.  We're now able to set events so they will occur some time in the future and the Event Engine will not evaluate them until they actually occur.
