### ISSUE TITLE
The mail-handler gets stuck on nameless emails

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#99]
Hi Dave, I have reviewed the same, here you have the explanation and some guidance to solve this in the future.

Just for your information, when this occurs, normally the description of the problem is at the top of every line logged by email handler.

The problem was generated here:

```
2020-03-28 19:21:11 : received mail with subject <b>register</b><br/><!DOCTYPE html><!-- Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;name&#039; cannot be null (SQL: insert into `users` (`name`, `email`, `updated_at`, `created_at`) values (?, david.rozak@darwinriver.com, 2020-03-28 19:21:11, 2020-03-28 19:21:11)) in file /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664 Caused by Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;name&#039; cannot be null
```

From my point of view seems that you started to use a new email, and this email does not provide the name or the php codes are not able to extract it from the email. 

You can see there that we are trying to insert this entry:

```
SQL: insert into `users` (`name`, `email`, `updated_at`, `created_at`) values (?, david.rozak@darwinriver.com, 2020-03-28 19:21:11, 2020-03-28 19:21:11))
```

And name is not provided, so probably a good fix could be to obtain the name from the first part of the email address, when unable to obtain it. What do you think?

When this happens, the email handler crashes and we are not able to remove this email from the queue, (exception there), and we enter a loop, always reading the same email.

We should protect this PHP part somehow in order to avoid this again, my proposal would be to:

1-Fill a default value, when none present / we are not able to obtain it.
2- Catch the exception and try to remove the corrupted messages from email handler's queue.

The only solution, for now (without touching the system), is the following (it is what I have done to restore the system):

1- Stop the sytem
2- As root user, go to /var/mail  and remove the inbox for both registrar and catchall, just remove the files present there for these users:

```
root@advolition:/var/mail# ls -tlasr
total 44
 4 drwxr-xr-x 14 root          root  4096 Jul  4  2018 ..
 0 -rw-------  1 root          mail     0 Jul 15  2019 root
 4 -rw-------  1 administrator mail  2320 Jul 23  2019 administrator
 0 -rw-------  1 forth         mail     0 Oct 20 20:29 forth
 8 -rw-------  1 registrar     mail  6849 Mar 29 01:12 registrar
24 -rw-------  1 catchall      mail 17421 Mar 29 01:15 catchall
 4 drwxrwsr-x  2 root          mail  4096 Mar 29 01:15 .

root@advolition:/var/mail# rm registrar catchall
```
3 - Remove/truncate huge log files generated (as forth user execute):

```
> cdlog
> rm email_handler_20200328.log email_handler_20200329.log
```

4 - Start the system again

So as a summary, we have a bug at the PHP codes when they are not able to retrieve the user's name. Feel free to decide what is your choice there, open a different issue for the same and assign it to me or Fernando if he is working at the PHP side now (just ensure that we do not modify codes at the same time).

Cheers! and go ahead with codvid19, we will defeat it!!!

_Originally posted by @crodnun in https://github.com/Darwin-River/Ex-Machinis/issues/51#issuecomment-605604655_

**Comment by freelancefrivas** [comment]
Ok, I changed the code so that it uses the first part of the email (before the '@') as name if it can't retrieve a name.

**Comment by freelancefrivas** [comment]
I uploaded it to exmachinis.com and ran the /get-mails script to check if something broke and it works...

**Comment by darozak** [comment]
Awesome! Thanks for doing that. @
